### ISSUE TITLE
Suggestion: Make commit messages more useful with very little changes

### ISSUE THREAD

**Issue by JelteF** [pgcentralfoundation/pgrx#1090]
Since last summer github allows you to configure your repo to take the PR description as the commit message by default:
https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

This makes commit messages much more useful in my experience. I don't know why it's not the default. My suggestion is to turn this setting on for this repo.

**Comment by workingjubilee** [comment]
I don't actually like including #issue_numbers in commit names because it causes problems later for subtrees and subtree splitting and conflates git repos with their hosting on GitHub, both of which I take a dim view of.

**Comment by workingjubilee** [comment]
To be precise: My issue is that I don't like it when "Fix issue #blah" appears in a commit message because then if that commit is ever included in another repo, it "fixes" the issue in the other repo as well, due to GitHub's extremely simplistic approach to that.

This, as you might imagine, can be problematic.

**Comment by JelteF** [comment]
I understand the issue you're describing and have definitely run into it myself a few times. But it seems rather orthogonal to the issue of having useful commit message bodies as a default message. You can still edit the commit message before pressing commit, so if desired you can still easily take out any references to issue numbers.

**Comment by workingjubilee** [comment]
Enabled.
