### ISSUE TITLE
Add support for Security Labels ?

### ISSUE THREAD

**Issue by daamien** [pgcentralfoundation/pgrx#1187]
Hi !

Thanks for this framework !  it is really helpful. 

Do you have plans to support Security Labels ? Although it is a very rare feature, it can be really powerful way to describe an ad-hoc security policy for an extension

At least functions like `register_label_provider` and `GetSecurityLabel` would quite usefull for me.

https://doxygen.postgresql.org/seclabel_8c.html
https://www.postgresql.org/docs/current/sql-security-label.html

Maybe it's already available but I couldn't find how in the docs...

**Comment by eeeebbbbrrrr** [comment]
I feel like you'd just want to write out the security label DDL in an `extension_sql!()` block?

Or are you asking for pgrx to include the internal functions (from `pg_sys::`) to manage them?  If this is the case, it'll be as easy as including `commands/seclabel.h` in the various `pgXX.h` header files pgrx has ()https://github.com/tcdi/pgrx/tree/master/pgrx-pg-sys/include).  

Would you like to send us a PR for that?

**Comment by daamien** [comment]
Hi @eeeebbbbrrrr 

Thanks for the quick reply, yes my need is to use internal functions through pg_sys.

I did not realize it was so straigthforward ! I will give it a try even though my knowledge in Rust is very limited.

**Comment by workingjubilee** [comment]
I'm going to close this as we now have the headers for writing `unsafe` code against, and writing a safer interface would be much more time consuming and _slightly_ niche, as noted, thus is not something I expect to happen right away. However we would be happy to accept a PR for such if it seemed well-designed!
