### ISSUE TITLE
Add support for "compiletest" tests

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [pgcentralfoundation/pgrx#1211]
Something that came out of PR #1210 is that there's some code patterns we'd like to ensure don't compile, which would be a way to help us enforce some borrowing rules/requirements around (at least) Spi.

That code is:

```rust
#[pg_test]
fn issue1209() -> Result<Option<String>, Box<dyn Error>> {
    // create the cursor we actually care about
    let mut res = Spi::connect(|c| {
        c.open_cursor("select 'hello' from generate_series(1, 10000)", None)
            .fetch(10000)
            .unwrap()
    });

    // here we just perform some allocations to make sure that the previous cursor gets invalidated
    for _ in 0..1000 {
        Spi::connect(|c| c.open_cursor("select 1", None).fetch(1).unwrap());
    }

    // later elements are probably more likely to point to deallocated memory
    for _ in 0..1000 {
        res.next();
    }

    // segfault
    Ok(res.next().unwrap().get::<String>(1)?)
}

#[pg_extern]
fn issue1209_prepared_stmt(q: &str) -> Result<Option<String>, Box<dyn std::error::Error>> {
    use pgrx::spi::Query;

    let prepared = { Spi::connect(|c| c.prepare(q, None))? };

    Ok(Spi::connect(|c| prepared.execute(&c, Some(1), None)?.first().get(1))?)
}
```

@workingjubilee suggested we use the `ui_test` crate (https://github.com/pgcentralfoundation/pgrx/pull/1210#issuecomment-1634730902).

**Comment by workingjubilee** [comment]
thomcc suggested [trybuild](https://docs.rs/trybuild/latest/trybuild/) is probably simpler and better for cargo-driven builds such as ours.

**Comment by thomcc** [comment]
compiletest/ui_test are both the wrong crate for this case (we might be able to make them work with substantial effort), they're more for the rustc_driver use case, like plrustc. For our case we would want `trybuild`: https://docs.rs/trybuild/latest/trybuild/
