### ISSUE TITLE
Is there a list of extensions created with pgrx?

### ISSUE THREAD

**Issue by craigpastro** [pgcentralfoundation/pgrx#1281]
👋 Hello!

I was just wondering if there was a list somewhere of extensions written using pgrx? If not, is it a nice idea to create one?

Thanks!

**Comment by eeeebbbbrrrr** [comment]
There's this fairly new website, but they don't seem to list any pgrx-based extensions yet:  https://pgt.dev

I know they're actively working on it.  If you're on twitter, you can ping "@tembo_io" or even their CEO, "@rywalker".

We don't keep a running list ourselves as it'd be a lot to keep up with.
`

**Comment by eeeebbbbrrrr** [comment]
Also, the "dependents" insight for our repo (I assume that's a public thing?) shows some users...

https://github.com/pgcentralfoundation/pgrx/network/dependents

**Comment by craigpastro** [comment]
Hi @eeeebbbbrrrr !

Thank you for the info.

> We don't keep a running list ourselves as it'd be a lot to keep up with.

Yeah, that is a good point. I guess I was thinking about an ADOPTERS.md file so that people who wrote an extension could add their extensions there themselves if they wanted. However, the dependents tab works quite fine. I forgot about that, thanks!
