### ISSUE TITLE
Request: #include "catalog/pg_am.h"

### ISSUE THREAD

**Issue by ccleve** [pgcentralfoundation/pgrx#1288]
Can we add catalog/pg_am.h to the headers?

I did it myself locally in v0.10.0 and it seems to work ok. I'd submit a PR, but it seems that the develop branch handles the NodeTag_T_* constants a bit differently -- NodeTag is an enum now? In any case, I can't compile my project against develop, which adds a bit complexity when doing a PR.

**Comment by workingjubilee** [comment]
Correct. NodeTag is an enum in Postgres, but more importantly, its values are for the most part ABI-unstable (excepting `T_Invalid`), so they aren't really "constants", and are a closed set (at least, a closed set at compile time). This aligns more closely with what Rust thinks of as an enum, so for the sake of everyone's sanity, it seems better to have it in a form that is easier to `match` on.

It's perfectly fine to PR it with minimal testing if it works against 0.10, I think, but I can get around to it in a bit.
