### ISSUE TITLE
Cast of a `varlena` into `varattrib_4b` neglects alignment

### ISSUE THREAD

**Issue by AndreaOddo89** [pgcentralfoundation/pgrx#1321]
I think I might have found a bug, that I noticed while deploying my extension in debug, since it kept on panicking with a `panic_misaligned_pointer_dereference`.
The `pgrx::valena::set_varsize_4b` method casts a `varlena` into a `varattrib_4b`, and also includes a comment about the safety of this cast: "```A varlena can be safely cast to a varattrib_4b```".
However, this appears not to be the case, since the alignment of a `varlena` as determined by `std::mem::align_of` is 1, while the alignment of a `varattrib_4b` is 4. This results in a panic whenever the `varlena` pointer is not aligned to 4, and in general can be considered undefined behavior.
This went unnoticed until recently since, starting with rust 1.70, alignment checks for pointer dereferences are inserted as debug assertions, manifesting the problem at runtime.

**Comment by AndreaOddo89** [comment]
I've prepared a test extension to demonstrate the problem, available here: [varlena_alignment](https://github.com/optionfactory/varlena_alignment).

After further analysis, it looks like:
* postgres' `varlena` has alignment requirement 1
* `pg_sys::varlena` correctly has the same alignment
* postgres' `varattrib_4b` has alignment 4, and requires the developer to verify alignment manually (see the definition of `VARSIZE_4B` and `SET_VARSIZE_4B` macros)
* `pg_sys::varattrib_4b` correctly has the same alignment
* `pgrx::set_varsize_4b` (and `pgrx::set_varsize` that delegates to it) incorrectly assume the passed `varlena` pointer to be 4-aligned and does not require the developer to ensure so in their SAFETY comments.

Possible solutions are either:
1. add the alignment requirement to the SAFETY comments for both `pgrx::set_varsize_4b` and `pgrx::set_varsize`;
2. add an assertion to check alignment before dereference in both `pgrx::set_varsize_4b` and `pgrx::set_varsize` and document the requirement in the rustdocs;
3. make both methods fallible (but it complicates the API for very little gain).

We checked the impact of adding the assertion as described in solution 2 by running some benchmarks, and it appears that the impact is likely negligible.

I can provide a PR based on your feedback.

**Comment by workingjubilee** [comment]
@AndreaOddo89 Apologies, I had seen this right before I left for vacation and then didn't think about it too hard. Yes, the first solution is preferable: these should be `unsafe fn` that document their requirements.

Actually, I don't really think we should offer `set_varsize` at all, as it just is an alias of `set_varsize_4b`, and a dev might imagine it is the write-equivalent of `varsize_any` (it's not). It only exists in Postgres because of legacy compat. Although perhaps making it panic on failure to align correctly would be a good idea.

**Comment by workingjubilee** [comment]
Hm. You know, looking at it, these are simple writes, and we can simply use `write_unaligned`, which shouldn't result in a performance regression in the general case.
