### ISSUE TITLE
Fixing sql-entity-graph and cargo-pgrx's dlopen hack

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1369]
I am like 80% sure I know how to fix pgrx-sql-entity-graph and cargo-pgrx in a way that makes it so we no longer have to do dlopen at build time or anything, but it's a fairly beefy refactor I don't have time to get into right now. It involves use of the [macro_magic](https://crates.io/crates/macro_magic) crate, or if necessary, extending it until it can fix the problem. However, I believe it is close to being able to solve the problem almost single-handedly.

I spoke to Ana about it and she agreed that it was basically what she would have done all along if it had been available at the time, instead of twiddling with linker hacks. It doesn't involve affecting anything we consider "public API", though it might affect our preferred design paths for future public APIs, so this should be done before adding any new design that involves extending our proc macros in significant ways that we want people to rely on.

Importantly, this would most likely enable building on Windows, and would definitely resolve issues re: surprising build instability, like
- https://github.com/pgcentralfoundation/pgrx/issues/1173

If anyone wants to do this in the next few months feel free to pepper me with questions.

**Comment by sam0x17** [comment]
happy to provide advice or context, author of `macro_magic` here :)

`macro_magic` is a clean, friendly wrapper around the very difficult to use decl macro callback pattern that people use (often via dtolnay's `tt_call` crate) to do "spooky action at a distance" type stuff with tokens of foreign items. In short, it will let you write proc and attribute macros that take one or more paths to items that have been decorated with `#[export_tokens]` and you can magically receive the tokens for these items at compile-time in addition to whatever tokens were passed to your proc/attribute macro.

It works really well when combined with the "outer macro pattern". Another key thing about `macro_magic` is it is 100% based on legal decl and proc macro callbacks, no futzing around in the `OUT_DIR` or anything cursed like that, so stuff based on this solution will continue working indefinitely as rust evolves in the future.

A really good demo of the power of this approach is my `supertrait` crate which simulates default associated types in stable, or the `derive_impl` macro in the `polkadot-sdk` ecosystem.

**Comment by thomcc** [comment]
I'm unsure how this can solve our issue that required `dlopen` to find generate the schema. Fundamentally `cargo-pgrx` and the cdylib we build are too separated, I don't think this trick can work across boundaries like that.

**Comment by sam0x17** [comment]
Yeah the only requirement is that the item you want to export and the place where you want to access its tokens are both under your control (i.e. you can add the `#[export_tokens]` attribute to the source item). So it can be a separate crate in a different workspace even, but you do have to attach `#[export_tokens]` or some alias of `#[export_tokens]` to the item. Not sure if that requirement can be met here
