### ISSUE TITLE
could not compile `thiserror-core` (lib)

### ISSUE THREAD

**Issue by anonrose** [pgcentralfoundation/pgrx#1390]
Unable to compile thiserror-core on Apple M1 Pro

```bash
cargo install --locked cargo-pgrx
```

error: could not compile `tracing` (lib)

Caused by:
  process didn't exit successfully: `/Users/kyle/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc --crate-name thiserror_core --edition=2018 /Users/kyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-core-1.0.38/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=129 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="std"' -C metadata=591680de5b1c7333 -C extra-filename=-591680de5b1c7333 --out-dir /var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY/release/deps -L dependency=/var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY/release/deps --extern thiserror_impl=/var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY/release/deps/libthiserror_core_impl-2dd8ba752c3420da.dylib --cap-lints allow` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: could not compile `tracing` (lib)

Caused by:
  process didn't exit successfully: `/Users/kyle/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc --crate-name tracing --edition=2018 /Users/kyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=129 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="attributes"' --cfg 'feature="default"' --cfg 'feature="std"' --cfg 'feature="tracing-attributes"' -C metadata=97592a113ca59b5b -C extra-filename=-97592a113ca59b5b --out-dir /var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY/release/deps -L dependency=/var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY/release/deps --extern cfg_if=/var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY/release/deps/libcfg_if-89dd00972f3cc5c6.rmeta --extern pin_project_lite=/var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY/release/deps/libpin_project_lite-e43aead989cdb62c.rmeta --extern tracing_attributes=/var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY/release/deps/libtracing_attributes-d6412df29fb9872b.dylib --extern tracing_core=/var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY/release/deps/libtracing_core-aedb14ef44dfeb8e.rmeta --cap-lints allow` (signal: 9, SIGKILL: kill)
error: failed to compile `cargo-pgrx v0.11.0`, intermediate artifacts can be found at `/var/folders/gj/0pc90fnn4c1f4qrk2zwfdwc80000gn/T/cargo-installIuUbsY`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by workingjubilee** [comment]
`rustc --version --verbose`?

**Comment by anonrose** [comment]
@workingjubilee 


rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: aarch64-apple-darwin
release: 1.73.0
LLVM version: 17.0.2

**Comment by anonrose** [comment]
@workingjubilee , I'm incredibly new(literally last night) to rust so I may be doing something wrong myself. Let me know how I can be helpful. I love the project, just want to use it, lol.

**Comment by workingjubilee** [comment]
Honestly, I'm genuinely not sure how this is happening. Can you try downgrading your Rust toolchain to 1.72.1 and retrying? ( I don't think 0.11 depends on 1.73 changes... )

**Comment by workingjubilee** [comment]
did you send the SIGKILL?

**Comment by anonrose** [comment]
I did not, just tried on 1.72.1 and same error.

**Comment by workingjubilee** [comment]
...that's really bizarre, I don't understand what's happening.

**Comment by workingjubilee** [comment]
Is this still happening with the latest Rust and pgrx 0.11.3?

**Comment by workingjubilee** [comment]
Okay, assuming no news is good news.
