### ISSUE TITLE
PGRX uses so many artifacts it destroys smaller drives

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1404]
It is hypothetically possible we could solve this, or at least look into solving this. Though honestly, this is a problem with Cargo in general, so I don't know if it is actually soluble.

> The default runners have sufficiently small disk space that they require hacks like clearing the entire target directory midway to clean out intermediates in order to complete our CI test run. Failure to do so, if we are generating sufficient intermediates, does not fail gracefully: it falls over wailing pathetically on whatever test put it over the disk limit. And it does not explain what happened. It just is a series of bizarre and opaque errors.
>
> As we have, in general, _insufficient_ testing, having a situation where, randomly, we are punished for adding tests, is not acceptable.

_Originally posted by @workingjubilee in https://github.com/pgcentralfoundation/pgrx/issues/1398#issuecomment-1817780536_

**Comment by workingjubilee** [comment]
Note that "make it obvious the tests failed because the filesystem is overflowing" would also qualify I think to solve this issue.

**Comment by BradyBonnette** [comment]
🙈

**Comment by workingjubilee** [comment]
Seems to have gotten a lot better. Not ideal tho'. But closing for now.
