### ISSUE TITLE
Compile failed pgrx-pg-sys v0.11.0 on centos7.6 with clang5 and gcc7

### ISSUE THREAD

**Issue by GPF199541** [pgcentralfoundation/pgrx#1407]
[root@cnsouth pg_bm25]# cargo build
   Compiling pgrx-pg-sys v0.11.0
error: failed to run custom build command for `pgrx-pg-sys v0.11.0`

Caused by:
  process didn't exit successfully: `/root/paradedb-0.3.10/target/debug/build/pgrx-pg-sys-04b4becf4858bdb6/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=PGRX_BUILD_VERBOSE
  cargo:rerun-if-env-changed=PGRX_PG_SYS_GENERATE_BINDINGS_FOR_RELEASE
  cargo:rerun-if-env-changed=PGRX_PG_CONFIG_PATH
  cargo:rerun-if-env-changed=PGRX_PG_CONFIG_AS_ENV
  cargo:rerun-if-env-changed=LLVM_CONFIG_PATH
  cargo:rerun-if-env-changed=LIBCLANG_PATH
  cargo:rerun-if-env-changed=LIBCLANG_STATIC_PATH
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=PGRX_PG_SYS_GENERATE_BINDINGS_FOR_RELEASE
  cargo:rerun-if-changed=include
  cargo:rerun-if-changed=cshim
  cargo:rerun-if-changed=/root/.pgrx/config.toml
  cargo:rerun-if-env-changed=PGRX_TARGET_INFO_PATH_PG15_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_TARGET_INFO_PATH_PG15
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER_PG15_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER_PG15
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER
  cargo:rerun-if-env-changed=PGRX_BINDGEN_NO_DETECT_INCLUDES_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_BINDGEN_NO_DETECT_INCLUDES

  --- stderr
  build_paths=BuildPaths { manifest_dir: "/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.0", out_dir: "/root/paradedb-0.3.10/target/debug/build/pgrx-pg-sys-dec9d4a8c938b421/out", src_dir: "/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.0/src/include", shim_src: "/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.0/cshim", shim_dst: "/root/paradedb-0.3.10/target/debug/build/pgrx-pg-sys-dec9d4a8c938b421/out/cshim" }
  Generating bindings for pg15
  /usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found
  Error: bindgen failed for pg15

  Caused by:
     0: Unable to generate bindings for pg15
     1: clang diagnosed error: /usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found

  Location:
      /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.0/build.rs:727:10

**Comment by GPF199541** [comment]
[root@cnsouth pg_bm25]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

**Comment by workingjubilee** [comment]
Please try again with `pgrx = "=0.11.1"` and the appropriate `cargo install cargo-pgrx` and so on.

**Comment by workingjubilee** [comment]
I am taking no news as good news, but please feel free to reopen this if paradedb's HEAD still doesn't build.
