### ISSUE TITLE
Default value for enum gets mapped incorrectly

### ISSUE THREAD

**Issue by alaneos777** [pgcentralfoundation/pgrx#1437]
Hi, I noticed the following: suppose that I have an enum like this with a default value:
```rust
#[derive(PostgresEnum, Serialize, Clone, Debug, Default)]
pub enum TestEnum {
    #[default]
    One,
    Two,
}
```
that gets mapped to SQL like this:
```sql
CREATE TYPE pg_catalog.TestEnum AS ENUM (
	'#[default] One',
	'Two'
);
```

As you can see, the default value has an unwanted extra `#[default] ` prefix. I'm using pgrx 0.11.2.

**Comment by eeeebbbbrrrr** [comment]
Woah. That’s clearly wrong!

I’ll take a look at this on Monday. Thanks for the report.
