### ISSUE TITLE
The error message on using incompatible pgrx versions should suggest a fix

### ISSUE THREAD

**Issue by MtnBiker** [pgcentralfoundation/pgrx#1444]
`The installed `cargo-pgrx` v0.11.2 is not compatible with the `pgrx = 0.10.2`, `pgrx-macros = 0.10.2`, `pgrx-sql-entity-graph = 0.10.2`, `pgrx-tests = 0.10.2` dependencies in `./Cargo.toml`. `cargo-pgrx` and pgrx dependency versions must be identical.`

How do I get out of this? I don't see anything about versions. I just installed 
➜ cargo install --locked cargo-pgrx
➜ cargo pgrx init --pg16 /Applications/Postgres.app/Contents/Versions/16/bin//pg_config
➜ cargo run --manifest-path ../tools/post-install/Cargo.toml -- pg_config=/Applications/Postgres.app/Contents/Versions/16/bin//pg_config
➜ cargo run --manifest-path ../tools/post-install/Cargo.toml -- /Applications/Postgres.app/Contents/Versions/16/bin//pg_config
➜ cargo pgrx install --release && \
cargo run --manifest-path ../tools/post-install/Cargo.toml -- /Applications/Postgres.app/Contents/Versions/16/bin//pg_config
Error:
   0: The installed `cargo-pgrx` v0.11.2 is not compatible with the `pgrx = 0.10.2`, `pgrx-macros = 0.10.2`, `pgrx-sql-entity-graph = 0.10.2`, `pgrx-tests = 0.10.2` dependencies in `./Cargo.toml`. `cargo-pgrx` and pgrx dependency versions must be identical.

I'm trying to install `timescaledb-toolkit` and this seemed like the path to get there. I'm using the Postgres.app on macOS. That seems to be the recommended way to run Postgres for Rails apps, but goes against the grain for installing most extensions. I've go the timescaledb extension installed, but need this one more extension. New to timescaledb

Thanks if you can point me in the right direction.

**Comment by eeeebbbbrrrr** [comment]
What that error message is telling you is that the `timescaledb-toolkit` crate wants pgrx v0.10.2 and you have installed, via `cargo install cargo-pgrx`, the latest version, which is v0.11.2.

What you can do is install the specific cargo-pgrx version it wants:

```shell
$ cargo install cargo-pgrx --version 0.10.2 --locked
```

Then you can probably continue with their installation instructions.  Any further problems are probably best addressed to the Timescale folks.

**Comment by MtnBiker** [comment]
Updated response.
Thank you. I could see that there was a recent version release and maybe something hadn't caught up. I didn't want to have to dive into Rust to find out how to do this.

Now I have a new error

```
➜ cargo pgrx install --release && \
cargo run --manifest-path ../tools/post-install/Cargo.toml -- pg_config
Error:
   0: $PGRX_HOME does not exist

Location:
   ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-config-0.10.2/src/lib.rs:536
```
Where is `$PGRX_HOME`? My limited understanding would think it would be `~/.cargo/` but that seems to be known to the script. 
OK, I put `export PGRX_HOME="${HOME}/.cargo/"` in .zshrc and all seems well now. But I had to guess at this while the script already seemed to know. But I'm out of my element here.
Thanks for keeping all of this going.

**Comment by workingjubilee** [comment]
We can recommend the correct install command as part of this error message.

**Comment by workingjubilee** [comment]
The other solution to suggest is "use `sed`", basically, and we should mention in the error message that the appropriate choice is based on whether they are a developer of that package (or willing to carry the relevant patch) or not. They should always prefer to update their install and package to the latest if they're a "dev", but users like MtnBiker should, generally speaking, simply downgrade.
