### ISSUE TITLE
Use shlex whenever we touch shell-argument-shaped-things directly

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1455]
in:
- https://github.com/pgcentralfoundation/pgrx/pull/1435
- https://github.com/pgcentralfoundation/pgrx/pull/1441

we do some things which would be better if we used [shlex](https://crates.io/crates/shlex).

**Comment by workingjubilee** [comment]
Note https://github.com/advisories/GHSA-r7qv-8r2h-pg27 which is now patched as of shlex 1.3.0 and is otherwise further proof of why we shouldn't be hand-rolling our own shell-touching code.

**Comment by NotGyro** [comment]
It looks like this has been solved in #1468. Let me know if this needs further changes.

**Comment by workingjubilee** [comment]
Oh, yeah! It seems done!
