### ISSUE TITLE
`pgrx init` - timed out reading response

### ISSUE THREAD

**Issue by NexRX** [pgcentralfoundation/pgrx#1467]
As the title describes, im timing out during the `cargo pgrx init` command.  specifically timing out to `https://www.postgresql.org/versions.rss`. Running a `curl` to this endpoint works fine.
I'm running Ubuntu 22.04.3 LTS (GNU/Linux 5.2.0 x86_64) if its relavent.

What I've tried:
- `--force` reinstalling with cargo
- Running a curl to this endpoint works fine.
- Trying after `ufw disable` (firewall disabled). 

Its a pretty fresh instance of Ubuntu and if it was for the last three points I'd assume a user error but it's a isolated incident on my system.

Here is the (s)hell history 😢 
```rust
$ cargo pgrx init
Error:
   0: unable to retrieve https://www.postgresql.org/versions.rss
   1: https://www.postgresql.org/versions.rss: Network Error: timed out reading response
   2: timed out reading response

Location:
   /home/nex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-pgrx-0.11.2/src/command/version.rs:42

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: cargo_pgrx::command::init::execute
      at /home/nex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-pgrx-0.11.2/src/command/init.rs:83
```

**Comment by eeeebbbbrrrr** [comment]
Does this happen every time?  The internet is flaky... maybe your tubes got clogged?

**Comment by NexRX** [comment]
Yeah it happens every time. I've done a couple force reinstalls and nothing changes it that ive tried. 
I do develop with rust so i have my suspicions it might be a cargo (with linux) thing but for some reason, it's isolated to pgrx for me.

btw sorry for the late reply, i didnt expect help so quick 😄

**Comment by workingjubilee** [comment]
@NexRX Can you try this on the latest develop branch? Clone the repo, `cargo install --path cargo-pgrx`, `rm ~/.pgrx` (or whatever), and then see if it still happens?

**Comment by NexRX** [comment]
Sorry again for the late reply. Busy work days. I tried clone and local install but no change, exact same behaviour. 

It could be my distro (version) or total PEBKAC. I mostly develop on windows but I'm only trying this on a Linux VPS.
Is there anything you need after installing cargo to get it network access? (Outside allowing/disabling UFW)

**Comment by NexRX** [comment]
Just an update, i tried installing and specifing pg16 and I also get a filesystem permission denied error. Does this give more clues as to whats going on?

```bash
$ cargo pgrx init --pg16 /usr/lib/postgresql/16/bin
     Creating PGRX_HOME at `/root/.pgrx`
   Validating /usr/lib/postgresql/16/bin
Error:
   0: Permission denied (os error 13)

Location:
   /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/convert/mod.rs:757

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: cargo_pgrx::command::init::init_pgrx
      at cargo-pgrx/src/command/init.rs:157
   1: cargo_pgrx::command::init::execute
      at cargo-pgrx/src/command/init.rs:85

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
```

I even tried just for the hell of it running the cargo stub with sudo but no dice `sudo ./cargo-pgrx pgrx`.

**Comment by eeeebbbbrrrr** [comment]
Postgres is not to be run as root. And pgrx shouldn’t be installed as root either.  Use a regular user account

**Comment by NexRX** [comment]
> Postgres is not to be run as root. And pgrx shouldn’t be installed as root either. Use a regular user account

100% agree, It was only an effort to debug permissions. 
I give up for now but if anyone has any steps to debug this, ill try them.

**Comment by workingjubilee** [comment]
> It could be my distro (version) or total PEBKAC. I mostly develop on windows but I'm only trying this on a Linux VPS.

You will have better luck with a WSL2 installation on your Windows machine.

**Comment by workingjubilee** [comment]
You can optionally try `cargo install --path cargo-pgrx --no-default-features --features native-tls` and `cargo install --path cargo-pgrx --no-default-features --features rustls` to see if either works. I suppose we could enable an alternative to the rss download, but this is the first time we've had anyone report simply insoluble network problems, with the array of options available.

**Comment by workingjubilee** [comment]
The 0.11.3 version of pgrx should have fixed networking. I'm not sure how to repro this (I use Linux every day for pgrx development and don't have this problem) so I'm going to close this issue, but feel free to reopen this if repro instructions appear.

**Comment by NexRX** [comment]
@workingjubilee Okay I understand. I would love to get this working but I think I'm an edge case. I'm trying to run this on a VPS using OpenVZ and i think thats the issue. (the OpenVZ part)

Do you have access to such a OpenVZ VPS? If not I'd be willing to give you access to a fresh one so you can reproduce more or less independantly. If so, I'll open up the issue, otherwise I'd hate to take up bandwidth.

**Comment by workingjubilee** [comment]
uh, no?

**Comment by workingjubilee** [comment]
I do essentially all of my development on a local machine without any virtualization or containerization in the way.

**Comment by NexRX** [comment]
Okay no worries.

Do you have any tips for trying to use this pgrx to build on one system for another system? That would be preferrable to me anyway. Even just a pointer to some docs would make me happy

**Comment by workingjubilee** [comment]
Do you mean cross-compiling? https://github.com/pgcentralfoundation/pgrx/blob/develop/docs/src/extension/build/cross-compile.md

**Comment by NexRX** [comment]
That is my best bet. Thanks for taking the time with me!

**Comment by spprashant** [comment]
@NexRX Kinda late, but FWIW I had the same issue with a brand new fedora install. Turning of SELinux worked for me.
