### ISSUE TITLE
`#[pg_extern]` functions cannot return `composite_type!` wrapped in `Result`

### ISSUE THREAD

**Issue by hoodiecollin** [pgcentralfoundation/pgrx#1470]
Based on this [snippet from the srf example](https://github.com/pgcentralfoundation/pgrx/blob/634c32ebeed2e3188f5ecebdfde5dd219df6ef9f/pgrx-examples/srf/src/lib.rs#L35C1-L41C2) _(included below)_, I assumed that a composite type could also be wrapped in a `Result` but I get an esoteric error. After looking at the offending code, `pgrx` tries to unwrap an option that should contain the name of the composite type.

Ideally I would like to use `Result` return types and `?` to keep my code easier to read rather than manually causing a `panic`.

```rust
#[pg_extern]
fn result_table() -> Result<
    Option<::pgrx::iter::TableIterator<'static, (name!(a, Option<i32>), name!(b, Option<i32>))>>,
    Box<dyn std::error::Error + Send + Sync + 'static>,
> {
    Ok(Some(TableIterator::new(vec![(Some(1), Some(2))])))
}
```

Below is a minimal example with the error log included too.

```rust

extension_sql!(
    r#"
    CREATE TYPE pool_stats_entry AS (
        max_open_connections int,
        open_connections int,
        in_use int,
        idle int,
        wait_count bigint,
        wait_duration bigint,
        max_idle_closed bigint,
        max_idle_time_closed bigint,
        max_lifetime_closed bigint
    );
    "#,
    name = "create_external_objects",
    bootstrap
);

const POOL_STATS_ENTRY: &str = "pool_stats_entry";

// This doesn't compile???
#[pg_extern(
    requires = [ "create_external_objects" ]
)]
pub fn pool_stats() -> Result<
    composite_type!('static, POOL_STATS_ENTRY),
    Box<dyn std::error::Error + Send + Sync + 'static>,
> {
    /*
    
    The application panicked (crashed).
    Message:  called `Option::unwrap()` on a `None` value
    Location: /Users/collinkokotas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-sql-entity-graph-0.11.2/src/pg_extern/entity/mod.rs:261
    
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
       0: cargo_pgrx::command::schema::generate_schema with pg_version=16.1 profile=Dev test=false path=/Users/collinkokotas/.pgrx/16.1/pgrx-install/share/postgresql/extension/pgmayan--0.0.0.sql features=["pg16"]
          at /Users/collinkokotas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-pgrx-0.11.2/src/command/schema.rs:176
       1: cargo_pgrx::command::install::install_extension with pg_version=16.1 profile=Dev test=false features=["pg16"]
          at /Users/collinkokotas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-pgrx-0.11.2/src/command/install.rs:114
       2: cargo_pgrx::command::run::run with pg_version=16.1 profile=Dev
          at /Users/collinkokotas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-pgrx-0.11.2/src/command/run.rs:94
       3: cargo_pgrx::command::run::execute
          at /Users/collinkokotas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-pgrx-0.11.2/src/command/run.rs:55
    
    Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
    Run with RUST_BACKTRACE=full to include source snippets.
    
    */
    todo!()
}


// But this does... 
#[pg_extern(
    requires = [ "create_external_objects" ]
)]
pub fn pool_stats_2() -> composite_type!('static, POOL_STATS_ENTRY) {
    todo!()
}

```

**Comment by eeeebbbbrrrr** [comment]
The (incredibly nasty) code around parsing the return type stuff, especially when Result or Option are involved, is probably buggy.  I'm not surprised that this case doesn't work.

We're working on quite a number of cleanups that will touch this code, the `composite_type!()` macro in general, and other related code.

In the mean time, I think you'll be best served to not return Result here and pepper in some `.expect()`s.  Or add another layer of indirection to you can centralize whatever `pool_stats()` is actually going to do so that the function itself delegates to that and then only manually handle 1 Result.

**Comment by hoodiecollin** [comment]
Thanks for the prompt reply, is there a roadmap doc or GH issue that outlines the scope of work for the cleanup you mentioned?

**Comment by workingjubilee** [comment]
In this particular area: only so-so. The work item is "certain parts of essentially everything had grown to be deeply logically entangled, and at some point something core to that tangle had become deeply incorrect, so now everything needs to be fixed". Also see:
- https://github.com/pgcentralfoundation/pgrx/pull/1420
- the recent commit history of pgrx-sql-entity-graph: https://github.com/pgcentralfoundation/pgrx/tree/7df371d0ef988ff1058d35f55670f289051861df/pgrx-sql-entity-graph
- the scattered issues on the ongoing lifetime problems that themselves have necessitated quite a lot of R&D just to begin to tackle them, such as
  - https://github.com/pgcentralfoundation/pgrx/issues/1383
  - https://github.com/pgcentralfoundation/pgrx/issues/1337
  - https://github.com/pgcentralfoundation/pgrx/issues/1209

I wouldn't say that the relevant Result/Option code is "buggy". As far as I know, anyways. It's the lifetime handling and not the Result/Option handling that's the problem, but the Result/Option handling is definitely... ad hoc. If you want to dream the dreams I have been having, the code for handling this stuff is mostly here:
- [pgrx-sql-entity-graph/src/pg_extern/returning.rs](https://github.com/pgcentralfoundation/pgrx/blob/a5625169297cd378c3d206cbf501025b5b2f6ba8/pgrx-sql-entity-graph/src/pg_extern/returning.rs)
- [pgrx-sql-entity-graph/src/used_type.rs](https://github.com/pgcentralfoundation/pgrx/blob/a5625169297cd378c3d206cbf501025b5b2f6ba8/pgrx-sql-entity-graph/src/used_type.rs)
