### ISSUE TITLE
Remove TableIterator-to-SetOfIterator remapping codegen?

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1484]
I think the way #1091 was solved leaves some lingering questions.

The error here is emitted from our code:

https://github.com/pgcentralfoundation/pgrx/blob/4fa87bd57d5e673e280c987a75cd8129ff349f43/pgrx/src/srf.rs#L96-L100

But we apparently "need" to convert the TableIterator into a SetOfIterator: https://github.com/pgcentralfoundation/pgrx/blob/5a45b3ae7ac3fe120181f4c50df689c1fb067c78/pgrx-sql-entity-graph/src/pg_extern/mod.rs#L557-L567

I find this to be a somewhat unclear statement, as it's not clear if the obligation is coming from Postgres or from our own code. It is strongly implied to be "from Postgres":

https://github.com/pgcentralfoundation/pgrx/blob/5a45b3ae7ac3fe120181f4c50df689c1fb067c78/pgrx-sql-entity-graph/src/pg_extern/mod.rs#L547-L549

However, what precisely seems to be happening is that we're the ones making the assumption that the return type must be a composite type if we're using a TableIterator. If this understanding is correct, then I think it should be written down as such. It also opens up an alternative solution that can move handling the one-item-tuple case out of the generated code, by using the fact this code is a trait impl and thus we can make generic impls do the lifting. And solving fewer problems during codegen is always preferable.

cc @eeeebbbbrrrr

**Comment by eeeebbbbrrrr** [comment]
A `RETURNS TABLE` function returns a set of that column's type.  In the case of a table returning 1 column, it's the type of that column.  In the multi-column case, Postgres makes a type to represent the attributes.

For example, notice that the **`prorettype`** for `foo()` is `2249` (which is `RECORDOID`) v/s the return type for `bar()` which is `25` (`TEXTOID`).

So pgrx has to switch modes here and just do what `RETURNS SET OF text` would do.

```sql
create function foo() returns table (a text, b text) language sql as $$ SELECT 'a', 'b' $$;
select * from pg_proc where proname = 'foo';
-[ RECORD 1 ]---+------------------
oid             | 4532350
proname         | foo
pronamespace    | 2200
proowner        | 10
prolang         | 14
procost         | 100
prorows         | 1000
provariadic     | 0
prosupport      | -
prokind         | f
prosecdef       | f
proleakproof    | f
proisstrict     | f
proretset       | t
provolatile     | v
proparallel     | u
pronargs        | 0
pronargdefaults | 0
prorettype      | 2249
proargtypes     | 
proallargtypes  | {25,25}
proargmodes     | {t,t}
proargnames     | {a,b}
proargdefaults  | 
protrftypes     | 
prosrc          |  SELECT 'a', 'b' 
probin          | 
prosqlbody      | 
proconfig       | 
proacl          | 


create function bar() returns table (a text) language sql as $$ SELECT 'a' $$;
select * from pg_proc where proname = 'bar';
-[ RECORD 1 ]---+-------------
oid             | 4532351
proname         | bar
pronamespace    | 2200
proowner        | 10
prolang         | 14
procost         | 100
prorows         | 1000
provariadic     | 0
prosupport      | -
prokind         | f
prosecdef       | f
proleakproof    | f
proisstrict     | f
proretset       | t
provolatile     | v
proparallel     | u
pronargs        | 0
pronargdefaults | 0
prorettype      | 25
proargtypes     | 
proallargtypes  | {25}
proargmodes     | {t}
proargnames     | {a}
proargdefaults  | 
protrftypes     | 
prosrc          |  SELECT 'a' 
probin          | 
prosqlbody      | 
proconfig       | 
proacl          | 
```

**Comment by workingjubilee** [comment]
@eeeebbbbrrrr I spent the time doing the git archaeology here because I found the wording confusing. By suggesting "RETURNS TABLE" must be "RETURNS SETOF" in this case, it didn't read correctly to me, because it needs to be doing a lot more changes to fully alter the function's *actual* return type and thus the *generated SQL*.

Unless you are referring *only* to the C and Rust implementation code.

**Comment by eeeebbbbrrrr** [comment]
> Unless you are referring only to the C and Rust implementation code.

Yes, I think.  Postgres doesn't rewrite the DDL to be "RETURNS SET OF text", but its SRF API expects the same return value -- a plain TEXT datum, rather than a HeapTuple with only 1 attribute.
