### ISSUE TITLE
We must unite `syn`

### ISSUE THREAD

**Issue by nyurik** [pgcentralfoundation/pgrx#1534]
In my experience, it is usually better to consolidate all dependencies in the root `/Cargo.toml`, and use `.workspace = true` everywhere else, even in cases where the dependency is used only in one project.  The reason for this is it keeps everything in one place, all versions are consistent across all projects, and does not require refactoring when a dependency starts being used in more than one project.

I will be happy to make this change if OK

**Comment by workingjubilee** [comment]
> even in cases where the dependency is used only in one project.

That is not currently my preference. I would prefer to keep dependencies locked down, preferably track the reasons for adding them, and deliberately induce friction to adding one.

> all versions are consistent across all projects,

Unfortunately, we have two different syns in this repo already.

**Comment by workingjubilee** [comment]
Also see https://github.com/pgcentralfoundation/pgrx/pull/1504 for more events of deliberate, seemingly-fruitless duplication, and increased friction on adding dependencies.

**Comment by workingjubilee** [comment]
We should fix the "have two `syn`s" part at least.

**Comment by nyurik** [comment]
Even if you do have multiple versions of sym, it would still be cleaner and easier to track if you use workspace for that.  You can just give two different aliases to them in the main Cargo.toml.  I have alleviated a lot of dep management pain this way, but obviously up to you.
