### ISSUE TITLE
Is `pgrx` capable of developing variadic functions?

### ISSUE THREAD

**Issue by bpsbits-org** [pgcentralfoundation/pgrx#1550]
Is `pgrx` capable of developing variadic functions?

Like the `concat ` function in PostgreSQL?

```rust
fn do_something_with_strings(in_names: Vec<Option<String>>) -> String {
// procedure
}
```

How to pass arguments into `in_names`?

```sql
select do_something_with_strings ('some', 'another', 'etc');
```

Providing an example would be greatly appreciated if at all feasible.

**Comment by eeeebbbbrrrr** [comment]
https://docs.rs/pgrx/latest/pgrx/datum/struct.VariadicArray.html

It works like our Array type, mostly. Looks like we don’t have an example of its usage except in our tests:  https://github.com/pgcentralfoundation/pgrx/blob/1f7bea78e2af6344f5609777143490b666a0d759/pgrx-tests/src/tests/variadic_tests.rs#L13
