### ISSUE TITLE
Document `cargo pgrx package` including `./sql`

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1582]
This is an undocumented feature that is useful for including extension upgrade scripts (`ALTER EXTENSION`), which currently must be written by hand.

**Comment by workingjubilee** [comment]
Apparently it works for all of `cargo pgrx {run,test,package}`.

**Comment by workingjubilee** [comment]
Assigning it to the person who knows it best~

**Comment by workingjubilee** [comment]
maybe we should write a comment in a file in the `./sql` directory like
```sql
-- cargo pgrx will copy .sql files from this directory when installing this extension
```

**Comment by eeeebbbbrrrr** [comment]
> `-- cargo pgrx will copy .sql files from this directory when installing this extension`

It only copies files in the format of `extname--oldver--newver.sql`.  All other files are ignored.  See PR #1725
