### ISSUE TITLE
Missing parameters in the `arg_walker` callback of `raw_expression_tree_walker` ?

### ISSUE THREAD

**Issue by daamien** [pgcentralfoundation/pgrx#1583]
Hi !

This may not be a bug but it is at least very weird :)

I'm trying  to use the `raw_expression_tree_walker` function, but I don't understant why the `arg_walker` callback function as no parameters... It's signature is 

`unsafe extern C fn() -> bool`

https://docs.rs/pgrx/latest/pgrx/pg_sys/fn.raw_expression_tree_walker.html

This callback seems useless if I can't inspect the node itself...

I would expect the walker callback signature to be 

`unsafe extern C fn(* mut Node, * c_void) -> bool`

Looking at the example below in the PostgreSQL code, I see that the tree_walker_callback used in raw_expression_tree_walker does have 2 parameters....

https://github.com/postgres/postgres/blob/master/src/backend/parser/analyze.c#L3576

Am I missing something obvious ?

**Comment by workingjubilee** [comment]
@daamien Mostly that Postgres 16 diffs this: https://github.com/postgres/postgres/commit/1c27d16e6e5c1f463bbe1e9ece88dda811235165

**Comment by workingjubilee** [comment]
@daamien I am happy to accept a PR that does the relevant mischief to make all versions conform to the interface that Postgres 16 describes via the appropriate function-pointer casting/transmutes.

**Comment by daamien** [comment]
I'm afraid this is way beyond my capabilities :/

**Comment by daamien** [comment]
Hi @workingjubilee 

As I'm moving forward with this, I realize that PR #1596 does cover `query_tree_walker`, `expression_tree_walker` and `raw_expression_tree_walker` but there's a few more functions that are also concerned by PG16's signature change

* query_or_expression_tree_walker
* range_table_entry_walker
* planstate_tree_walker
* range_table_walker

As far as I can tell, with their current signature those 4 functions a pretty much useless at the moment.
 
Now I guess I should be able to copycat what you did on #1596 and submit a patch to fix those 4 functions....  Should I make a single PR for them all or a distinct PR for each of them ?

**Comment by workingjubilee** [comment]
@daamien Feel free to take all of them in one.
