### ISSUE TITLE
Backwards compatibility with new UDF signature

### ISSUE THREAD

**Issue by alaneos777** [pgcentralfoundation/pgrx#1590]
Hi, suppose that I have version `1.0.0` of my extension and contains this UDF:
```rust
#[pg_extern]
fn my_udf(a: i32, b: default!(i32, 1)) -> i32 {
   // ...
}
```
and currently I have one PG instance running this extension in version `1.0.0`, and everything is OK.

Now, in version `2.0.0` I decide to add a new default argument in `my_udf`:
```rust
#[pg_extern]
fn my_udf(a: i32, b: default!(i32, 1), c: default!(i32, 1)) -> i32 {
   // ...
}
```

If I only update the `2.0.0` shared library in the PG instance but not the extension script (for example, I don't run `ALTER EXTENSION` and `\dx` still shows version `1.0.0`), after invoking the UDF with arguments `a` and `b` I get the following error:
```
ERROR:  index out of bounds: the len is 2 but the index is 2
```
which makes sense, because the old UDF `1.0.0` signature from sql script only sends two arguments, but the new function in the `2.0.0` shared library expects three.

What is the best way in this case to achieve backwards compatibility from an old extension UDF signature against a new shared library which expects more arguments? I'd like to receive the default values for the newly added arguments instead of the above error.

I thought of just overloading the function such that we keep `my_udf` function old signature in rust and add a new one, something like this:
```rust
#[pg_extern(name = "my_udf")]
fn my_udf(a: i32, b: default!(i32, 1)) -> i32 {
   my_udf_version_2_0_0(a, b, 1)
}

#[pg_extern(name = "my_udf")]
fn my_udf_version_2_0_0(a: i32, b: default!(i32, 1), c: default!(i32, 1)) -> i32 {
  // ...
}
```
but I have many functions like that, I'd be writing much additional code just for that purpose.

Thanks.

**Comment by workingjubilee** [comment]
> If I only update the 2.0.0 shared library in the PG instance but not the extension script (for example, I don't run ALTER EXTENSION and \dx still shows version 1.0.0), after invoking the UDF with arguments a and b I get the following error:

Pardon, are you sure that this entire problem is not due to not running `ALTER EXTENSION`?

Can you share a more complete backtrace if at all possible? You may need to set `RUST_BACKTRACE=1` to get such.

I think you are trying to design around what may simply be a bug. It seems probable the bug is in our code. Also can you report what version of pgrx you're using?

**Comment by workingjubilee** [comment]
Adding a new default argument should permit callers using the previous arity, according to my understanding of how CREATE FUNCTION works, how default arguments work, and how Postgres calls its functions.

**Comment by alaneos777** [comment]
I'm using pgrx `0.11.2`. Let me share the detailed steps, so you can reproduce it:

1. UDF signature in extension version `1.0.0`:
```rust
#[pg_extern]
fn my_udf(a: i32, b: default!(i32, 1)) -> i32 {
    a + b
}
```
2. Build the extension shared library, schema and run `create extension`. Test that the UDF works:
```
alaneos777@DESKTOP-87O1FE1:~/pgrx-udf$ RUST_BACKTRACE=1 cargo pgrx run pg15
       Using CliArgument("pg15") and `pg_config` from /usr/lib/postgresql/15/bin/pg_config
    Stopping Postgres v15
    Building extension with features pg15
     Running command "/home/alaneos777/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo" "build" "--features" "pg15" "--no-default-features" "--message-format=json-render-diagnostics"
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
  Installing extension
     Copying control file to /usr/share/postgresql/15/extension/pgrx_udf.control
     Copying shared library to /usr/lib/postgresql/15/lib/pgrx_udf.so
 Discovering SQL entities
  Discovered 1 SQL entities: 0 schemas (0 unique), 1 functions, 0 types, 0 enums, 0 sqls, 0 ords, 0 hashes, 0 aggregates, 0 triggers
     Writing SQL entities to /usr/share/postgresql/15/extension/pgrx_udf--1.0.0.sql
    Finished installing pgrx_udf
    Starting Postgres v15 on port 28815
    Re-using existing database pgrx_udf
psql (15.6 (Ubuntu 15.6-1.pgdg22.04+1))
Type "help" for help.

pgrx_udf=# create extension pgrx_udf;
CREATE EXTENSION
pgrx_udf=# \dx
                  List of installed extensions
   Name   | Version |   Schema   |         Description          
----------+---------+------------+------------------------------
 pgrx_udf | 1.0.0   | public     | pgrx_udf:  Created by pgrx
 plpgsql  | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

pgrx_udf=# select my_udf(5, 7);
 my_udf 
--------
     12
(1 row)

pgrx_udf=#
```
3. Update extension version to `2.0.0` in Cargo.toml and modify the UDF to:
```rust
#[pg_extern]
fn my_udf(a: i32, b: default!(i32, 1), c: default!(i32, 1)) -> i32 {
    a + b + c
}
```
4. Build the extension shared library and schema, but don't run `alter extension` (I don't even have a script for that yet). Now this time if we call the UDF with two arguments it doesn't work:
```
alaneos777@DESKTOP-87O1FE1:~/pgrx-udf$ RUST_BACKTRACE=1 cargo pgrx run pg15
       Using CliArgument("pg15") and `pg_config` from /usr/lib/postgresql/15/bin/pg_config
    Stopping Postgres v15
    Building extension with features pg15
     Running command "/home/alaneos777/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo" "build" "--features" "pg15" "--no-default-features" "--message-format=json-render-diagnostics"
   Compiling pgrx_udf v2.0.0 (/home/alaneos777/pgrx-udf)
    Finished dev [unoptimized + debuginfo] target(s) in 6.07s
  Installing extension
     Copying control file to /usr/share/postgresql/15/extension/pgrx_udf.control
     Copying shared library to /usr/lib/postgresql/15/lib/pgrx_udf.so
 Discovering SQL entities
  Discovered 1 SQL entities: 0 schemas (0 unique), 1 functions, 0 types, 0 enums, 0 sqls, 0 ords, 0 hashes, 0 aggregates, 0 triggers
     Writing SQL entities to /usr/share/postgresql/15/extension/pgrx_udf--2.0.0.sql
    Finished installing pgrx_udf
    Starting Postgres v15 on port 28815
    Re-using existing database pgrx_udf
psql (15.6 (Ubuntu 15.6-1.pgdg22.04+1))
Type "help" for help.

pgrx_udf=# select my_udf(5, 7);
ERROR:  index out of bounds: the len is 2 but the index is 2
DETAIL:  
   0: pgrx_pg_sys::submodules::panic::register_pg_guard_panic_hook::{{closure}}::{{closure}}
             at /home/alaneos777/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.2/src/submodules/panic.rs:312:39
   1: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
   2: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
   3: pgrx_pg_sys::submodules::panic::register_pg_guard_panic_hook::{{closure}}
             at /home/alaneos777/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.2/src/submodules/panic.rs:309:9
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
   5: std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
   8: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   9: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  10: core::panicking::panic_bounds_check
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:208:5
  11: pgrx::fcinfo::pg_12_13_14_15::get_nullable_datum
             at /home/alaneos777/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-0.11.2/src/fcinfo.rs:305:13
  12: pgrx::fcinfo::pg_12_13_14_15::pg_getarg
             at /home/alaneos777/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-0.11.2/src/fcinfo.rs:230:21
  13: pgrx_udf::my_udf_wrapper::my_udf_wrapper_inner
             at /home/alaneos777/pgrx-udf/src/lib.rs:6:1
  14: pgrx_udf::my_udf_wrapper::{{closure}}
             at /home/alaneos777/pgrx-udf/src/lib.rs:6:1
  15: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  16: __rust_try
  17: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  18: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  19: pgrx_pg_sys::submodules::panic::run_guarded
             at /home/alaneos777/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.2/src/submodules/panic.rs:408:11
  20: pgrx_pg_sys::submodules::panic::pgrx_extern_c_guard
             at /home/alaneos777/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.2/src/submodules/panic.rs:385:11
  21: my_udf_wrapper
             at /home/alaneos777/pgrx-udf/src/lib.rs:6:1
  22: <unknown>
  23: <unknown>
  24: standard_ExecutorRun
  25: <unknown>
  26: PortalRun
  27: <unknown>
  28: PostgresMain
  29: <unknown>
  30: PostmasterMain
  31: main
  32: <unknown>
  33: __libc_start_main
  34: _start

pgrx_udf=# \dx
                  List of installed extensions
   Name   | Version |   Schema   |         Description          
----------+---------+------------+------------------------------
 pgrx_udf | 1.0.0   | public     | pgrx_udf:  Created by pgrx
 plpgsql  | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

pgrx_udf=# 
```

Of course, if I prepare a script `pgrx_udf--1.0.0--2.0.0.sql` and then run `ALTER EXTENSION pgrx_udf UPDATE` it will work (or even drop and create the extension again), but my goal is to have the ability to invoke the UDF using an outdated UDF definition in postgres but using the new shared library (using the default values for the missing arguments).

**Comment by workingjubilee** [comment]
> but my goal is to have the ability to invoke the UDF using an outdated UDF definition in postgres but using the new shared library.

I don't think we want to support that use-case, I'm sorry. It doesn't seem well-motivated. Could you explain _why_ this is important? I am open to reconsidering if your desire is persuasive.

What is happening here is that you are saying to Postgres "the number of arguments to this function is N", but then saying to us, "the number of arguments is N + 1". The result is that we create a slice of NullableDatums _using the known number of arguments that Postgres is aware of_, but index the slice _at the position you tell us the arguments are at_. In what I would expect is 99.7% of cases, a mismatch here is simply a bug. Even with default arguments, it is still a bug in 95% of cases. As this is _wildly_ unsafe code we're dealing with, deep in the heart of the framework's logic, it is a very bad bug for us to risk by allowing this, even for the case when we have a default argument.

**Comment by workingjubilee** [comment]
I should note that the fix making the code tolerant to this case is _relatively_ obvious:

- Make a fallible version of `pg_get_nullable_datum`: https://github.com/pgcentralfoundation/pgrx/blob/5f0db5818851f2ce651ca443b1b546d72d001929/pgrx/src/fcinfo.rs#L154-L170
- Make the code that handles arg unpacking aware of when an argument to a function is defaulted, then expand appropriate code that handles the fallible case: https://github.com/pgcentralfoundation/pgrx/blob/5f0db5818851f2ce651ca443b1b546d72d001929/pgrx-sql-entity-graph/src/pg_extern/mod.rs#L391-L435

However, "obvious" is not the same as "easy to implement". This would require working backwards to the last place we interact with `default!()` and recording that. That would require reworking a lot of code to pipe that data forward.

You _can_ simply accept the `FunctionCallInfo` and unpack the args yourself, of course.

A PR that makes these changes within pgrx may also be sufficiently persuasive, but you would be touching a lot of code that is of dubious soundness already, and I would expect such cases to be left better than you found it.

**Comment by alaneos777** [comment]
Thanks for the detailed explanation, I guess for now I'll just use `FunctionCallInfo`. Do you have any examples of how can I use it? The whole reason behind all of this is just curiosity, I thought of this use case and wanted to do some testing around it.

**Comment by workingjubilee** [comment]
Thank you for raising this issue! It prompted me to take a look at our argument-handling code and I spotted severe soundness issues in two functions. I have put up the PR to fix them.

The code for manually handling arguments like that is in `pgrx::fcinfo`. It is very `unsafe`. It is an option, but I do not actually recommend it. Your code will remain sound with the pattern you mentioned. You are taking things into your own hands by interacting with FunctionCallInfo directly.

**Comment by workingjubilee** [comment]
My apologies we don't have a better handling for this. It is my intention to add better support for variadic fn in the future: https://github.com/pgcentralfoundation/pgrx/issues/1428

For now, judging by your preference to use one of the workarounds available, I will close this.
