### ISSUE TITLE
Inconsistency between code and documentation

### ISSUE THREAD

**Issue by YichiZhang0613** [pgcentralfoundation/pgrx#1613]
I think there is inconsistency between code and documentation in pgrx-develop/pgrx-pg-sys/src/submodules/htup.rs, "Will panic if `attnum` is less than zero" indicates that the constraint is attnum >= 0 while the code check attnum > 0. Maybe it should be "Will panic if `attnum` is less than or equal to zero"?
```rust
/// # Panics
///
/// Will panic if `attnum` is less than zero
#[inline(always)]
unsafe fn fastgetattr(
    tup: *mut HeapTupleData,
    attnum: i32,
    tupleDesc: TupleDesc,
    isnull: &mut bool,
) -> Datum {

	assert!(attnum > 0);
```

**Comment by workingjubilee** [comment]
Oh, yes, probably! Please feel free to send in a PR!
