### ISSUE TITLE
Add `cargo pgrx upgrade` type functionality

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1647]
`cargo pgrx` packages a minimum amount of toml-inspecting and toml-manipulating code of: "a lot". We should just allow updating the pgrx versions for someone.

**Comment by workingjubilee** [comment]
Bigger changes could be made automagical-ish in the future, but this would be the basic one.

**Comment by NotGyro** [comment]
Implemented in https://github.com/pgcentralfoundation/pgrx/pull/1687

**Comment by workingjubilee** [comment]
Yes, this has been completely fixed!
