### ISSUE TITLE
Omit lifetime of wrapper function.

### ISSUE THREAD

**Issue by my-vegetable-has-exploded** [pgcentralfoundation/pgrx#1649]
Thanks for your great work!

I found the warper function contains unnecessary lifetime. And the rustc compiler warns that lifetime parameter `'a` never used.

```rust
#[pgrx::pg_extern(immutable, strict, parallel_safe)]
fn _vectors_vector_accum<'a>(
    mut state: AccumulateState<'a>,
    value: Vecf32Input<'_>,
) -> AccumulateState<'a> 
```

After expanding 

```rust
pub unsafe extern "C" fn _vectors_vector_accum_wrapper<'a>(
    _fcinfo: ::pgrx::pg_sys::FunctionCallInfo,
) -> ::pgrx::pg_sys::Datum {
    #[allow(non_snake_case)]
    unsafe fn _vectors_vector_accum_wrapper_inner<'a>(
        _fcinfo: ::pgrx::pg_sys::FunctionCallInfo,
    ) -> ::pgrx::pg_sys::Datum { 
```

The lifetime is useless for _vectors_vector_accum_wrapper.

If this issue makes sense, I'd like to open a pr to fix it.

**Comment by workingjubilee** [comment]
I would accept a PR that applies `#[allow(unused_lifetimes)]` to the wrapper function.

**Comment by workingjubilee** [comment]
If I remember correctly, actually omitting the "unused" lifetime does not actually work in all cases, which is why a PR simply omitting the lifetime may not work out. I would be happy to review such a PR, however.

**Comment by my-vegetable-has-exploded** [comment]
> If I remember correctly, actually omitting the "unused" lifetime does not actually work in all cases, which is why a PR simply omitting the lifetime may not work out. I would be happy to review such a PR, however.

Thanks for pointing out it. But I think that both `wrapper` function and `wrapper_inner`  function just take `    _fcinfo: ::pgrx::pg_sys::FunctionCallInfo` as arguments and return `::pgrx::pg_sys::Datum` , those type don't contain lifetime.  I think maybe your concern is that `#resolved_ty` contains lifetime<'a> in `::pgrx::fcinfo::pg_getarg::<#resolved_ty>` . I am not sure whether lifetime is nessary for `::pgrx::fcinfo::pg_getarg`.

https://github.com/pgcentralfoundation/pgrx/blob/bce089e55bd77f1eeada904a9e8d482842994d56/pgrx-sql-entity-graph/src/pg_extern/mod.rs#L427-L429 

> I would accept a PR that applies `#[allow(unused_lifetimes)]` to the wrapper function.

Get! It is a really easier way to add  `#![allow(unused_lifetimes, clippy::extra_unused_lifetimes)]`.

Thanks @workingjubilee
