### ISSUE TITLE
Add CI clippy test to auto-generated code

### ISSUE THREAD

**Issue by nyurik** [pgcentralfoundation/pgrx#1741]
User code with these enabled causes clippy warnings. Please add an integration test as part of CI to ensure generated code does not trigger any warnings, e.g. `cargo clippy --workspace --all-targets --bins --tests --lib --benches --examples -- -D warnings` and `RUSTDOCFLAGS="-D warnings" cargo doc --no-deps`

```rust
#![warn(unused_qualifications)]
#![warn(clippy::pedantic)]
```

See also #1740

**Comment by workingjubilee** [comment]
Clippy not recognizing code is macro-generated is a clippy bug.

**Comment by workingjubilee** [comment]
I will not do what you ask.

I will do https://github.com/pgcentralfoundation/pgrx/pull/1744

I hope it suffices.
