### ISSUE TITLE
Copying data files to target

### ISSUE THREAD

**Issue by jawj** [pgcentralfoundation/pgrx#1751]
My extension code needs access to a static data file, which therefore needs to be copied to the target alongside the extension `.control` file and the other generated/compiled files.

Sorry if I missed something, but I couldn't figure out from the docs how best to achieve this. Ideas?

**Comment by workingjubilee** [comment]
@jawj Is this file's data fixed at compile-time? If so, the best way would be `static WHATEVER: &[u8] = include_bytes!(filepath);`

Otherwise we'd need to extend cargo-pgrx's abilities here.

**Comment by jawj** [comment]
Yes, thanks: that works nicely.
