### ISSUE TITLE
How to create `VariadicArray`?

### ISSUE THREAD

**Issue by 4kimov** [pgcentralfoundation/pgrx#1768]
I'm trying to create something simple like this; however, latest `pgrx` version is giving me errors:

```rust
let numbers: VariadicArray<i64> = VariadicArray::from(vec![1, 2, 3]);
```

How can I create this?

P.S: I'm trying to create it so I can test a function like this:

```rust
pub fn encode(numbers: VariadicArray<i64>) -> Result<String, PgError> {
	...
}
```

**Comment by workingjubilee** [comment]
can you be excruciatingly specific with "latest" and "errors"

**Comment by 4kimov** [comment]
Yep, for sure!

```
Rust 1.79.0
pgrx = "=0.11.4"
pgrx-tests = "=0.11.4"
```

Test code:

```rust
// Extension code goes here...

#[cfg(any(test, feature = "pg_test"))]
#[pg_schema]
mod tests {
    use pgrx::prelude::*;
    use pgrx::VariadicArray;
    use super::*;

    #[pg_test]
    fn test_simple() {
		let numbers: VariadicArray<i64> = VariadicArray::from(vec![1, 2, 3]);
		assert_eq!("86Rf07".to_string(), sqids_encode(numbers).unwrap());
    }
}

#[cfg(test)]
pub mod pg_test {
    pub fn setup(_options: Vec<&str>) {
    }

    pub fn postgresql_conf_options() -> Vec<&'static str> {
        vec![]
    }
}
```

Error:

```
❯ cargo pgrx test
       Using DefaultFeature("pg13") and `pg_config` from /Users/dev/.pgrx/13.15/pgrx-install/bin/pg_config
CARGO_TARGET_DIR="/Users/dev/git/sqids-postgresql/target" PGRX_ALL_FEATURES="false" PGRX_BUILD_PROFILE="dev" PGRX_FEATURES="pg13 pg_test" PGRX_NO_DEFAULT_FEATURES="true" PGRX_NO_SCHEMA="false" "/Users/dev/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo" "test" "--features" "pg13 pg_test" "--no-default-features"
   Compiling pg_sqids v0.1.0 (/Users/dev/git/sqids-postgresql)
error[E0308]: mismatched types
   --> src/lib.rs:227:57
    |
227 |         let numbers: VariadicArray<i64> = VariadicArray::from(vec![1, 2, 3]);
    |                                           ------------------- ^^^^^^^^^^^^^ expected `VariadicArray<'_, i64>`, found `Vec<{integer}>`
    |                                           |
    |                                           arguments to this function are incorrect
    |
    = note: expected struct `pgrx::VariadicArray<'_, i64>`
               found struct `Vec<{integer}>`
```

**Comment by workingjubilee** [comment]
Huh, it seems we don't have a reasonable conversion from Vec to VariadicArray.

That's the "reflexive From".

**Comment by workingjubilee** [comment]
Usually, @4kimov, we use SPI and support functions to do the "coercion" between Vecs and VariadicArray, or we use `iter().collect()` to do it the other way around, this can be witnessed in https://github.com/pgcentralfoundation/pgrx/blob/a898087e249d30185bd06a1360d2dfb389f1636c/pgrx-tests/src/tests/array_tests.rs

This is somewhat unergonomic but VariadicArray is a wrapper around a large-ish internal data structure of Postgres with a very nonintuitive layout, for which I have used dark sorcery to make it "go fast" when calculating over large arrays.

**Comment by 4kimov** [comment]
@workingjubilee ah, I see. I looked through the link, but still having hard time wrapping my head around it.

Any suggestion on how I could test [this function](https://github.com/sqids/sqids-postgresql/blob/main/src/lib.rs#L12)? Alternatively, maybe I shouldn't be using `VariadicArray` at all? I only chose it because it allows us to [do this](https://github.com/sqids/sqids-postgresql?tab=readme-ov-file#-examples).

Edit: Honestly, I don't even care if my tests are in SQL, as opposed to Rust (if there's a way to do that).

**Comment by workingjubilee** [comment]
I think using VariadicArray as the interface of a `pg_extern` function is fine, it's just hard to unit test since what you _really_ want is to issue queries to the tests.

The "Server Programming Interface" is what allows us to issue queries using FFI code, like [SELECT](https://docs.rs/pgx/latest/pgx/spi/struct.SpiClient.html#method.select), which is why it is abundant in our test suite.

There is an intention to add an SQL-driven regression test functionality but it has not happened yet.

**Comment by 4kimov** [comment]
Ah, ok this makes more sense now. Looks like the following does the trick:

```rust
#[cfg(any(test, feature = "pg_test"))]
#[pg_schema]
mod tests {
	use pgrx::prelude::*;

	#[pg_test]
	fn test_sqids_encode() {
		let result = Spi::get_one("SELECT sqids_encode(1, 2, 3);");
		assert_eq!(result.unwrap(), Some("86Rf07".to_string()));
	}
}
```

---

@workingjubilee I'm going to close the issue. Thank you very much for your time, guidance and the library (which is very neat)!
