### ISSUE TITLE
`cargo pgrx init` should allow specifying one single version

### ISSUE THREAD

**Issue by johanatan** [pgcentralfoundation/pgrx#1775]
rather than just defaulting to installing and configuring 6 versions.

also, on an M3 Mac, this process for all 6 took on the order of ~3 days to complete (which seems excessive).

**Comment by eeeebbbbrrrr** [comment]
You have a few different options:

To install just one version (XX = major version number)
```shell
$ cargo pgrx init --pgXX=download
```

Or, if you want to use an existing Postgres installation, that also has the server headers:

```shell
$ cargo pgrx init --pgXX=/path/to/pgXX/bin/pg_config
```

EDIT:  Check out the docs for `cargo-pgrx` too:  https://github.com/pgcentralfoundation/pgrx/blob/develop/cargo-pgrx/README.md

As far as taking 3 days to compile, this is the first I've ever heard of that.  A few minutes, sure.  Especially on an M3 Mac, not a few days.  Any chance you can dig into that a bit more?  Some kind of network latency issue, maybe?

**Comment by workingjubilee** [comment]
other people with M3 Macs have done this in a much shorter time. my first instincts would be to ask if you are perhaps using the thinnest Mac Air, which are ironically somewhat notoriously _bad at airflow_. but even that wouldn't explain it. might take a few hours, but 3 days?

otherwise the only way I can imagine it taking 3 entire days is if you had put it in an oven so it was constantly throttling instead of dissipating heat.

**Comment by johanatan** [comment]
It is a MacBook Air actually and in an air conditioned room with plenty of space for ventilation around the laptop, just sitting on a desk. Most of the time was spent on the "INSTALLING ..." and "COMPILING ..." phases for each of the 6 versions and in both cases, 4-5 of them finished pretty quickly and only a couple of stubborn ones took the bulk of the time (and it was different versions between the two). I didn't want to disturb it so I didn't do too much digging but yea it was painful lol.

**Comment by workingjubilee** [comment]
> MacBook Air

well... you have chosen maybe one of the worst possible Macs for this, but it still sounds _vanishingly unlikely_. like I said, a few hours at most, but really, it should still be under 1 hour for any recent modern hardware.

but which of the versions were "stubborn"?

now I can only imagine something actively hanging somewhere.

**Comment by eeeebbbbrrrr** [comment]
Were you also transcoding 4k videos and mining crypto?

It’s not that that I don’t believe you, but 3 days is nearly impossible for me to swallow. 

My M1 mini and M1 MBP do this in just a few minutes.

**Comment by workingjubilee** [comment]
I guess one of the worst possible Macs would actually be a bargain basement Intel Mac from over a decade ago.

hold on, I think I have one of those.

**Comment by eeeebbbbrrrr** [comment]
This doesn't prove anything, but `cargo pgrx init` on my M1 Mini, just now, took almost exactly 5 minutes.  This is the slowest computer I own.

```shell
$ time cargo pgrx init                
   Discovered Postgres v11.22, v12.19, v13.15, v14.12, v15.7, v16.3
  Downloading Postgres v16.3 from https://ftp.postgresql.org/pub/source/v16.3/postgresql-16.3.tar.bz2
  Downloading Postgres v15.7 from https://ftp.postgresql.org/pub/source/v15.7/postgresql-15.7.tar.bz2
  Downloading Postgres v14.12 from https://ftp.postgresql.org/pub/source/v14.12/postgresql-14.12.tar.bz2
  Downloading Postgres v13.15 from https://ftp.postgresql.org/pub/source/v13.15/postgresql-13.15.tar.bz2
  Downloading Postgres v11.22 from https://ftp.postgresql.org/pub/source/v11.22/postgresql-11.22.tar.bz2
  Downloading Postgres v12.19 from https://ftp.postgresql.org/pub/source/v12.19/postgresql-12.19.tar.bz2
     Removing /Users/e_ridge/.pgrx/16.3
     Removing /Users/e_ridge/.pgrx/11.22
    Untarring Postgres v16.3 to /Users/e_ridge/.pgrx/16.3
    Untarring Postgres v11.22 to /Users/e_ridge/.pgrx/11.22
     Removing /Users/e_ridge/.pgrx/15.7
    Untarring Postgres v15.7 to /Users/e_ridge/.pgrx/15.7
  Configuring Postgres v11.22
     Removing /Users/e_ridge/.pgrx/12.19
  Configuring Postgres v16.3
    Untarring Postgres v12.19 to /Users/e_ridge/.pgrx/12.19
     Removing /Users/e_ridge/.pgrx/14.12
     Removing /Users/e_ridge/.pgrx/13.15
    Untarring Postgres v14.12 to /Users/e_ridge/.pgrx/14.12
    Untarring Postgres v13.15 to /Users/e_ridge/.pgrx/13.15
  Configuring Postgres v15.7
  Configuring Postgres v12.19
  Configuring Postgres v14.12
  Configuring Postgres v13.15
    Compiling Postgres v16.3
    Compiling Postgres v11.22
    Compiling Postgres v15.7
    Compiling Postgres v12.19
    Compiling Postgres v13.15
    Compiling Postgres v14.12
   Installing Postgres v11.22 to /Users/e_ridge/.pgrx/11.22/pgrx-install
   Installing Postgres v12.19 to /Users/e_ridge/.pgrx/12.19/pgrx-install
   Installing Postgres v13.15 to /Users/e_ridge/.pgrx/13.15/pgrx-install
   Installing Postgres v15.7 to /Users/e_ridge/.pgrx/15.7/pgrx-install
   Installing Postgres v16.3 to /Users/e_ridge/.pgrx/16.3/pgrx-install
   Installing Postgres v14.12 to /Users/e_ridge/.pgrx/14.12/pgrx-install
   Validating /Users/e_ridge/.pgrx/11.22/pgrx-install/bin/pg_config
   Validating /Users/e_ridge/.pgrx/12.19/pgrx-install/bin/pg_config
   Validating /Users/e_ridge/.pgrx/13.15/pgrx-install/bin/pg_config
   Validating /Users/e_ridge/.pgrx/14.12/pgrx-install/bin/pg_config
   Validating /Users/e_ridge/.pgrx/15.7/pgrx-install/bin/pg_config
   Validating /Users/e_ridge/.pgrx/16.3/pgrx-install/bin/pg_config
cargo pgrx init  1164.76s user 314.43s system 633% cpu 3:53.34 total
```

![Screenshot 2024-07-11 at 1 41 44 PM](https://github.com/pgcentralfoundation/pgrx/assets/5117238/16250c39-c54c-4ead-950e-6168be7dd493)

I was thinking... could you have been doing this such that the target directory `~/.pgrx/` (assuming you didn't set PGRX_HOME) is on your iCloud?  That would probably be quite terrible to compile Postgres 6x over the Internet.  I'm grasping at straws here...

**Comment by workingjubilee** [comment]
oh ew, device sync on every file? that's horrifying.

**Comment by johanatan** [comment]
> I was thinking... could you have been doing this such that the target directory `~/.pgrx/` (assuming you didn't set PGRX_HOME) is on your iCloud?  That would probably be quite terrible to compile Postgres 6x over the Internet.  I'm grasping at straws here...
> 

No, but that's not a bad idea: iCloud has definitely screwed me in other ways recently. 

This was actually inside the pg16-all timescaledb-ha image for ARM since that's the image I ultimately want to run the produced artifact (pg_graphql) on. I did the same process recently on my Mac Studio except for the x86_64 image (so running under Rosetta) and it didn't take absurdly long. I had expected ARM on ARM to be lightning fast. :)

**Comment by eeeebbbbrrrr** [comment]
> This was actually inside the pg16-all timescaledb-ha image for ARM

I don't know what that means?

**Comment by workingjubilee** [comment]
It _should_ be pretty damn fast, but your Mac Studio will kick your Mac Air's ass any day of the week, even with one hand tied behind its back. But you didn't need me to tell you that.

Do you mean to say you're running stuff inside Docker? Hmm. Docker does... weird things on Mac, sometimes...

**Comment by johanatan** [comment]
> > This was actually inside the pg16-all timescaledb-ha image for ARM
> 
> 
> 
> I don't know what that means?

Sorry, docker container/image.

**Comment by johanatan** [comment]
> Do you mean to say you're running stuff inside Docker? Hmm. Docker does... weird things on Mac, sometimes...

Yes, good point, docker is the most likely culprit & wasn't part of the equation on the Mac Studio (I simply did cross-compilation on the host via Rosetta, rather than anything inside a container). I attempted that actually here as well before resorting to docker but it was incredibly hard to do for Mac ARM to Linux ARM.

**Comment by workingjubilee** [comment]
Are you using hypervisor.framework or virtualization.framework for Docker?

**Comment by johanatan** [comment]
I'm not sure. Whichever one is included by default with Docker Desktop. I had read that the worst performance issues had been resolved in the default installation so I didn't dig too much but perhaps that's still not the case.

**Comment by eeeebbbbrrrr** [comment]
I don't know that there's any action we need to take here, so I'm going to close this issue.

**Comment by bpsbits-org** [comment]
> I'm not sure. Whichever one is included by default with Docker Desktop. I had read that the worst performance issues had been resolved in the default installation so I didn't dig too much but perhaps that's still not the case.

Switched to `podman` while ago due the perfomance issues of `docker` on macOS.
