### ISSUE TITLE
How to generate upgrade paths?

### ISSUE THREAD

**Issue by KaiserKarel** [pgcentralfoundation/pgrx#1781]
I'd like to upgrade the extension, and for that I need to create upgrade paths. Is there a guide on how to write and include these in a release?

**Comment by eeeebbbbrrrr** [comment]
Hopefully this section of the `cargo-pgrx` README docs gets you pointed in the right direction:

https://github.com/pgcentralfoundation/pgrx/blob/v0.12.0-beta.3/cargo-pgrx/README.md#extension-version-upgrade-scripts

To see a practical timeline of this, ZomboDB's repo might show you one way to manage things:  <https://github.com/zombodb/zombodb/tree/master/sql>.

If you have other questions, don't hesitate to ask.
