### ISSUE TITLE
extremely random macOS breakage?

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1788]

**Comment by workingjubilee** [comment]
@bayandin We install rustup in our macOS CI, no? Why does it suddenly not work anymore?

**Comment by bayandin** [comment]
`pgrx` on macOS CI uses `rustup-init` formula that's preinstalled on macOS runners. 
In https://github.com/Homebrew/homebrew-core/pull/177582, `rustup-init` has been made keg-only (to avoid conflicting with the `rust` formula). 
To make it work again we need to add `rustup-init -y` call

**Comment by workingjubilee** [comment]
I see.

I have just decided to apply https://github.com/pgcentralfoundation/pgrx/pull/1789 instead. I don't really want to go chasing random changes in homebrew packaging anymore.
