### ISSUE TITLE
copy_sql_files for version update sql can overwrite generated schema

### ISSUE THREAD

**Issue by timwaizenegger** [pgcentralfoundation/pgrx#1800]
### Background
If we release a new version `2.0.0` of our extension that changes the name or type of some PG objects, we can provide a script to perform an update of the existing objects in the PG database.

These scripts follow a naming pattern required by PG; for an update of `abc` from version 1.0.0 to 2.0.0 I need to provide a script called `abc--1.0.0--2.0.0.sql`; see https://www.postgresql.org/docs/current/extend-extensions.html#EXTEND-EXTENSIONS-UPDATES

In the dir `./sql` (of a pgrx project) we can provide these version update scripts and pgrx will package/install them for us. Nice!

### Problem / Name conflict
The code to pick up these static update scripts is here: https://github.com/pgcentralfoundation/pgrx/blob/6dfb9d1eaeb70aa76035799970e073b1e8417998/cargo-pgrx/src/command/install.rs#L389

It looks for files with names that match: `if filename.starts_with(&format!("{extname}--")) && filename.ends_with(".sql") {` and then copies those into the extension target.

But this naming pattern _also_ matches the name of the sql file that contains the generated schema (that pgrx generated from rust code); compare https://github.com/pgcentralfoundation/pgrx/blob/6dfb9d1eaeb70aa76035799970e073b1e8417998/cargo-pgrx/src/command/install.rs#L352

And that schema file gets generated _before_ the version-update scripts are copied. 

**So If I place "any" file into `./sql` that has the same name as the generated schema, it will be copied and will overwrite the generated schema.**

### Is this actually a problem?
I believe it is; for the following reasons:
- there is no obvious indication that this happened; the file just gets overwritten silently
- resulting behavior doesn't point to this root cause; depending on what you do, things might continue to work
  - tests usually fail because the test PG instance is temporary so without the generated schema, you're probably missing some objects from the test setup
- the "offending" file in my case was a static SQL script that I wanted to include with `extension_sql_file`. The examples for this actually use the `./sql` directory; e.g. here https://github.com/pgcentralfoundation/pgrx/blob/6dfb9d1eaeb70aa76035799970e073b1e8417998/pgrx-examples/custom_sql/src/lib.rs#L75
  - (some other examples use `./static` which would avoid the problem)
- it's somewhat natural to use the "offending" filename for the static sql file (even though none of your examples actually do that; they all avoid the issue)
  - after all, that's the name that the resulting file will have in the packaged extension
  - the PG docs use this filename pattern
  - i.e. `abc-2.0.0.sql` for my example above

### How to avoid this?
- stricter filename matching for copying version update files (i.e. check for presence of both versions; not just prefix/suffix)
- while copying the version update scripts, compare to the filename of `dest`; i.e. detect the overwrite case and warn/panic

**Comment by timwaizenegger** [comment]
FYI, I'd be happy to propose a fix for this; let me know what you think!

**Comment by eeeebbbbrrrr** [comment]
> So If I place "any" file into ./sql that has the same name as the generated schema, it will be copied and will overwrite the generated schema.

"Doctor, it hurts when I do this...".  "Well, don't do that!".

That said, sure, we'd happily accept a PR to tighten this up a bit.  From a practical standpoint, I think it'd be confusing for a project to name a .sql file as `{extname}--XXXXXX.sql` but I do agree that we shouldn't blindly overwrite the schema file we just generated -- that's definitely kinda mean!

I think probably the answer is to improve the pattern check to make sure it's in the form of `{extname}--$A--$B.sql` when deciding what to copy.  That's the only pattern that Postgres' "CREATE EXTENSION ... UPDATE;` is going to recognize.  The values for $A and $B, however, can be anything -- they're not required to follow a "semver"-like pattern.  They could be "cat" and "dog" for all we care.

**Comment by workingjubilee** [comment]
We should probably emit a warning if something looks particularly off here... I don't know if we'd warn if we encounter any such file `sql/*.sql` that we wouldn't copy over? But probably we should consider doing so (though only once for all files).

We should keep running though, and yes, behave correctly, if that's easy enough.

**Comment by timwaizenegger** [comment]
> We should probably emit a warning if something looks particularly off here... I don't know if we'd warn if we encounter any such file `sql/*.sql` that we wouldn't copy over? But probably we should consider doing so (though only once for all files).

Only the version-update scripts (with names like `abc--1.0.0--2.0.0.sql`) get copied over. Any other static SQL needs to be explicitly imported via the pgrx macro `extension_sql_file`. Those files could be in `sql/` or in a different dir; that makes it a bit hard to come up with useful conditions for a warning.

I think an alternative here would be to replace the implicit copy logic and require people to explicitly define the version update files; similar to the other static SQL.

**Comment by workingjubilee** [comment]
Hm, I suppose.

And I would rather not add more logic inside pgrx that makes code aware of files around it in manners that are not direct transclusion.

**Comment by timwaizenegger** [comment]
Ok, I finished up my PR and did some basic testing: https://github.com/pgcentralfoundation/pgrx/pull/1817

let me know what you think!
