### ISSUE TITLE
📚 `cargo pgrx package` == `Unable to find pg_config on the system $PATH`

### ISSUE THREAD

**Issue by bpsbits-org** [pgcentralfoundation/pgrx#1830]
`cargo pgrx package` causes an error:

```
Error: 
   0: Unable to find `pg_config` on the system $PATH
   1: No such file or directory (os error 2)
```

I do not want to install `postgresql` server on machine. 
For development `pgrx` already installed these.

But how to use `cargo pgrx package` correctly to build distro?

**Comment by eeeebbbbrrrr** [comment]
> But how to use cargo pgrx package correctly to build distro?

well...

> I do not want to install postgresql server on machine.

This is how `cargo pgrx package` works.  It uses a distro-managed Postgres installation for the proper compilation options and directory layout.

Sorry Charlie, but you'll have to do it.  :)

**Comment by bpsbits-org** [comment]
> > But how to use cargo pgrx package correctly to build distro?
> 
> well...
> 
> > I do not want to install postgresql server on machine.
> 
> This is how `cargo pgrx package` works. It uses a distro-managed Postgres installation for the proper compilation options and directory layout.
> 
> Sorry Charlie, but you'll have to do it. :)

Thank you for response. 

But I want to ship it on container based postrges?

**Comment by workingjubilee** [comment]
We have to have access to the headers of the Postgres you're actually going to build against or the compilation is subject to various inaccuracies.

**Comment by workingjubilee** [comment]
It's *possible* we could build in support to allow you to say "I swear my Postgres will be completely stock" and then we use the stock headers, but that would have to be opt-in. It wouldn't let you then install a distro's Postgres and reliably run extensions on that, because distros patch their software, including Postgres.

**Comment by eeeebbbbrrrr** [comment]
Requiring the actual postgres you want to build against is no different than any PGXS C extension.  

Our machinery is a bit more, but the ultimate requirements are the same.  

I dunno if we could invent some kind of lightweight build tool?

**Comment by bpsbits-org** [comment]
@eeeebbbbrrrr :
> This is how `cargo pgrx package` works. It uses a distro-managed Postgres installation for the proper compilation options and directory layout.

@workingjubilee 
> We have to have access to the headers of the Postgres you're actually going to build against or the compilation is subject to various inaccuracies.

Thank you fo response. 

## Dirty solution

For `podman`. Should work on `docker` too if to update some parts of code.

Works fine on `macOS` with `Podman Desktop`.

`Containerfile.pg16` is in project root directory. `build.amd64.pg16.sh` is in `scripts` directory

Run from projct root: 

```shell
bash ./scripts/build.amd64.pg16.sh
```

Pretty robust solution, but it works. With some optimisations this could be the part of new project?

### `scripts/build.amd64.pg16.sh`

```shell
#!/usr/bin/env bash
# scripts/build.amd64.pg16.sh

# Define locations
MS_START=$(date +%s)
readonly CONTAINER_NAME="build-pgrx"
readonly PGRX_BUILDER_FILE="${BASH_SOURCE[0]}"
PGRX_BUILDER_DIR="$(dirname "$PGRX_BUILDER_FILE")"
PGRX_PROJECT_DIR="$(dirname "$PGRX_BUILDER_DIR")"
readonly MS_START
readonly PGRX_BUILDER_DIR
readonly PGRX_PROJECT_DIR

# Check if the container exists
if podman ps -a --format "{{.Names}}" | grep -qw "$CONTAINER_NAME"; then
    echo -e "Old build container \`$CONTAINER_NAME\` exists."
    # Stop the container if it's running
    if podman ps --format "{{.Names}}" | grep -qw "$CONTAINER_NAME"; then
        echo -e "Stopping old build container \`$CONTAINER_NAME\` ..."
        podman stop "$CONTAINER_NAME"
    fi
    # Remove the container
    echo -e "Removing old build container \`$CONTAINER_NAME\` ..."
    podman rm "$CONTAINER_NAME"
else
    echo -e "Old build container \`$CONTAINER_NAME\` does not exist."
fi

# Go to the project directory
cd "$PGRX_PROJECT_DIR" || exit 1

# Clean build directory
mkdir -p ./build
rm -rf ./build/{*,.[!.]*,..?*}

# Build extension
podman build --arch amd64 -f Containerfile.pg16 -t build-pgrx:snapshot .

# Run container that contains final build
podman run -d --name "$CONTAINER_NAME" localhost/build-pgrx:snapshot

# Copy build to ./build
podman cp "$CONTAINER_NAME":/root/pgrx-build/packed/distro.zip ./build

# Time spent
MSR_END=$(date +%s)
readonly MSR_END
TIME_SPENT=$(( MSR_END - MS_START ))
echo "Elapsed time: $TIME_SPENT seconds"

exit 0
```

### `Containerfile.pg16`

```Dockerfile
# ------------------------------------------------------------
# Builds pgrx based postgres extension
# Containerfile.pg16
# ------------------------------------------------------------
# podman build --arch amd64 -t build-pgrx:snapshot .
# Please note that some outputs are silenced to reduce the noise.
# If you encounter problems, disable silnecers to see an output.
#
FROM docker.io/library/postgres:16 AS postgres_pgrx_build

ENV POSTGRES_PASSWORD='********'

# Add required components
RUN apt-get -qq update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -qq -y \
    bison  \
    build-essential  \
    ccache  \
    curl  \
    flex  \
    git  \
    libclang-dev  \
    libreadline-dev  \
    libssl-dev  \
    libxml2-dev  \
    libxml2-utils  \
    libxslt-dev  \
    pkg-config  \
    postgresql-server-dev-16 \
    xsltproc  \
    zip \
    zlib1g-dev < /dev/null > /dev/null
RUN apt-get clean

# Install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y  2>/dev/null >/dev/null
ENV PATH="/root/.cargo/bin:${PATH}"
RUN chmod +x /root/.cargo/env && /root/.cargo/env
RUN cargo --version

# Install pgrx
RUN cargo install --locked cargo-pgrx 2>/dev/null >/dev/null
RUN cargo pgrx init --pg16 /usr/lib/postgresql/16/bin/pg_config
RUN cargo pgrx --version

# Prepare data for build
RUN mkdir -p /root/pgrx-build
RUN rm -rf /root/pgrx-build/*
RUN mkdir -p /root/pgrx-build/distro; mkdir -p /root/pgrx-build/packed; mkdir -p /root/pgrx-build/target/release
WORKDIR /root/pgrx-build
COPY . .

# Build
RUN cargo pgrx package
RUN ls -l /root/pgrx-build/target/release
RUN ls -l /root/pgrx-build/distro

# Compress build
RUN find /root/pgrx-build/target/release -type d -name '*-pg16' | head -n 1 > /root/pgrx-build/distro-dir.txt
RUN export SRC_DIR=$(cat /root/pgrx-build/distro-dir.txt) && echo "$SRC_DIR" && cp -r "$SRC_DIR"/* /root/pgrx-build/distro
RUN cd /root/pgrx-build/distro && zip -q -r /root/pgrx-build/packed/distro.zip .
RUN ls -l /root/pgrx-build/packed
```
