### ISSUE TITLE
Can `#[pg_extern]` functions be split out into separate files/modules?

### ISSUE THREAD

**Issue by jawj** [pgcentralfoundation/pgrx#1833]
I have an experimental extension that's becoming a bit unwieldy, since all its Postgres-exposed `#[pg_extern]` functions live in one module in a single, long `src/lib.rs`.

Is there a way to split out individual functions (or groups of functions) into other files? I've tried to do this using Rust modules, but so far it hasn't worked.

I've had the error `File modules (like mod name;) aren’t able to be supported due to [rust/#54725](https://github.com/rust-lang/rust/issues/54725)`. But I'm not sure if that means what I'm trying to do isn't possible, or only that I'm going about it the wrong way (I'm pretty new to both Rust and pgrx).

What isn't working currently looks something like the following:

`src/lib.rs`
```rust
use pgrx::prelude::pg_schema;
mod mysubmod;
 
#[pg_schema]
mod myschema {
    use pgrx::prelude::*;
    pgrx::pg_module_magic!();

    pub use super::mysubmod::*;
}
```

`src/mysubmod.rs`
```rust
use pgrx::prelude::*;

#[pg_extern(immutable, strict)]
pub fn myfn() -> String {
    "xyz"
}
```

**Comment by eeeebbbbrrrr** [comment]
I don't know what that error is telling you, but that doesn't come from pgrx.  Sounds like you've got some general weirdness in your crate structure or module file naming.  I'm not sure.

The answer is "of course you can put `#[pg_extern]` functions in different modules".  Most pgrx extensions are built that way, including one or two of our examples.  See https://github.com/zombodb/zombodb for example.

If you want to come up with a complete standalone example and upload a tarball here, perhaps I can take a look.  I'm much better at fixing rust compilation errors than I am reverse engineering code from an error.

**Comment by jawj** [comment]
Thanks. I checked a few of the examples in the main repo and they all seemed to have everything in `lib.rs`. I'll check out ZomboDB and that will hopefully make things clearer. If not, I'll provide a minimal example.

**Comment by eeeebbbbrrrr** [comment]
Our `custom_types/` example uses multiple .rs files.

**Comment by jawj** [comment]
OK. It turned out the main change I needed was to wrap the exported functions in the same `mod name {}` block in every module file.

Thanks again for your help.
