### ISSUE TITLE
`String::from_datum()` of a null value led to a segmentation fault

### ISSUE THREAD

**Issue by lizardoluis** [pgcentralfoundation/pgrx#1852]
The `FromDatum` implementation for `String` fails when a null value is passed.

Example: 

```
let val: pg_sys::Datum = pg_sys::Datum::null();
let is_null: bool = true;

unsafe {
    match String::from_datum(val, is_null) {   // <- this seg fault
        Some(_) => println!("Returned a value"),
        None => println!("Returned none"),
    };
}
```

In this example, the function should return `None` when a null value is passed. However, the current implementation does not properly handle the null case for String and crash.

Unlike other `from_polymorphic_datum()` implementations, the `String` implementation does not verify if the value is null before attempting to process it. You can see this in the code here:

https://github.com/pgcentralfoundation/pgrx/blob/5eadffb64d37ba08a5cc8060f1ed59153c6f8edd/pgrx/src/datum/from.rs#L400-L422

It used to work on v0.11.4. 
Fails now on v0.12.3. 
pg16

I think the issue was introduced on https://github.com/pgcentralfoundation/pgrx/commit/beb79011a377bb96c34fcc50ae2d652aa1419eb5

**Comment by eeeebbbbrrrr** [comment]
Huh.  Thanks for the report.  That's definitely not the correct behavior!

**Comment by eeeebbbbrrrr** [comment]
PR up at https://github.com/pgcentralfoundation/pgrx/pull/1853.

Once CI passes I'll go ahead and publish a new release.  This is pretty severe.

**Comment by lizardoluis** [comment]
Thank you very much. 
That was quick

**Comment by eeeebbbbrrrr** [comment]
we aim to please!

But yikes!  This is quite bad.  Embarrassed we missed this.
