### ISSUE TITLE
How to ensure All Memory Allocation in a pgrx-based Plugin uses palloc Instead of Native malloc?

### ISSUE THREAD

**Issue by softhuafei** [pgcentralfoundation/pgrx#1874]
We are developing a plugin based on Greenplum and pgrx. In Greenplum, any memory allocated through palloc is tracked (via memory context), allowing us to monitor the total memory usage for each node. When the memory used by a query exceeds the gp_vmem_protect_limit, we can promptly cancel the query. However, many memory allocation operations in Rust are performed using native malloc, which means this part of the memory cannot be accounted for or managed.

Is it possible for us to implement std::alloc::GlobalAlloc based on palloc and pfree, so that all memory allocations in Rust can be tracked? This would enable us to use Greenplum's resource queue (resqueue) or resource group (resgroup) to control the memory usage of the processes, thus avoiding system-level OOM killers.

**Comment by YohDeadfall** [comment]
Switching all allocations to `palloc` will result in breaking of the code soundness and an undefined behavior, so such allocations should be done manually if needed. Though all types convertible to datums use `palloc` when that conversion happens.

If you use the nightly toolchain then `MemCx<'mcx>` comes with the `Allocator` trait implemented for it. That might help.

**Comment by workingjubilee** [comment]
Specifically, `malloc` creates **un**bounded lifetime allocations[^0] and the Rust typesystem models this. However, `palloc` creates bounded lifetime allocations. This has to be modeled correctly or you can, for instance, put these allocations inside a `static`, which will persist between transactions.

If you use a global allocator that operates like this, it becomes unsound, unfortunately, unless you *always* allocate in the Top context. But then, of course, you have a memory leak!

[^0]:  or at least, "process lifetime bound", which is functionally "forever" when we're talking about code that has the perspective of "inside a process".
