### ISSUE TITLE
Expose Postgres Index Free Space Map (FSM) functions

### ISSUE THREAD

**Issue by travisturner** [pgcentralfoundation/pgrx#1899]
It would be useful to have access to the Free Space Map (FSM) functions available for index relations found in
[/src/backend/storage/freespace/indexfsm.c](https://github.com/postgres/postgres/blob/master/src/backend/storage/freespace/indexfsm.c)

```
BlockNumber GetFreeIndexPage(Relation rel);
void RecordFreeIndexPage(Relation rel, BlockNumber freeBlock);
void RecordUsedIndexPage(Relation rel, BlockNumber usedBlock);
void IndexFreeSpaceMapVacuum(Relation rel);
```

I'm submitting this issue based on the following instructions from the README, but let me know if I should take a different approach. Thanks!

```
Not all of Postgres' internals are included or even wrapped. This isn't due to
it not being possible, it's simply due to it being an incredibly large task. If
you identify internal Postgres APIs you need, open an issue and we'll get them
exposed, at least through the pgrx::pg_sys module.
```

**Comment by eeeebbbbrrrr** [comment]
Sure. We can include these in the next release.
