### ISSUE TITLE
Can't get `cargo pgrx init` to compile Postgres on more than one core

### ISSUE THREAD

**Issue by jawj** [pgcentralfoundation/pgrx#1916]
I'm setting up an Ubuntu 24.04 VM (using https://multipass.run on an M3 Pro MacBook Pro) to compile and test a pgrx extension.

I set the VM up with 4 cores, 4GB RAM and 20GB disk.

When I run `cargo pgrx init --pg16 download`, Postgres compilation is stuck on one core, and it doesn't help to specify `--jobs 4`. That makes it very slow, of course.

Subsequently, `cargo pgrx install` is able to max out all 4 cores.

Any ideas what could be the problem here?

This is everything that's run on a fresh VM:

```bash
sudo apt update
sudo apt upgrade -y
sudo apt install -y build-essential pkg-config libssl-dev libreadline-dev zlib1g-dev libicu-dev libclang-dev

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. "$HOME/.cargo/env"

cargo install --locked cargo-pgrx@0.12.5
cargo pgrx init --pg16 download
```

**Comment by SteveLauC** [comment]
Hi, [I also want this](https://github.com/pgcentralfoundation/pgrx/issues/1903), from the source code the `--jobs` option won't be passed to `make world-bin`, instead, it is passed to the jobserver:

https://github.com/pgcentralfoundation/pgrx/blob/f4d707476845e8badec265fcf9bf025748cace24/cargo-pgrx/src/command/init.rs#L89-L99

So I guess this is the reason behind your issue.

**Comment by SteveLauC** [comment]
> Subsequently, `cargo pgrx install` is able to max out all 4 cores.

`cargo-pgrx` does not have an `install` sub-command, do you mean `cargo install`?

**Comment by SteveLauC** [comment]
From the source code, the value configured in `--jobs` will be passed to [`Client::new(limit)`](https://docs.rs/jobslot/latest/jobslot/struct.Client.html#method.new), looks like this `jobslot` library is used to limit the number of uppermost `make` command that could be executed at the same time, and if so, I guess it is not related to `make -j`

**Comment by SteveLauC** [comment]
Related to #1903

**Comment by jawj** [comment]
OK, closing as a dupe of #1903.
