### ISSUE TITLE
`cargo install --locked cargo-pgrx` command not working in apple silicon

### ISSUE THREAD

**Issue by yacineb** [pgcentralfoundation/pgrx#1944]
<img width="862" alt="image" src="https://github.com/user-attachments/assets/6eb186e4-741d-44fb-9c8d-d6aac448246f">

**Comment by workingjubilee** [comment]
@yacineb Screenshots are not acceptable bug reports. You did not specify what version you tried to install. Please reopen if you are willing to provide more details in text form.
