### ISSUE TITLE
Adapting Apache/Cloudberry

### ISSUE THREAD

**Issue by roseduan** [pgcentralfoundation/pgrx#1952]
Apache/Cloudberry(https://github.com/apache/cloudberry) is a MPP database based on postgresql, an open source alternative to Greenplum Database.

If we enable pgrx in Cloudberry,  we can use it to build MPP based extensions in rust.

I am willing to contribute, let me know your thoughts.

**Comment by tuhaihe** [comment]
Hi @roseduan thanks for creating this issue.

There was one thread on this topic for your information: https://github.com/pgcentralfoundation/pgrx/issues/1179. 

I guess this project would like to have the PR for Cloudberry as talked above.

**Comment by eeeebbbbrrrr** [comment]
My comment still applies:  https://github.com/pgcentralfoundation/pgrx/issues/1179#issuecomment-2300491088

We won't accept a PR without the necessary resources to support it long-term.  If y'all are serious, please get in contact with @ChronicallyJD and you'd likely want to discuss support options from @workingjubilee and myself as well.
