### ISSUE TITLE
Enable LTO for cargo-pgrx

### ISSUE THREAD

**Issue by zamazan4ik** [pgcentralfoundation/pgrx#1954]
Hi!

Could you please enable Link-Time Optimization ([LTO](https://doc.rust-lang.org/rustc/codegen-options/index.html#lto)) for the `cargo-pgrx` extension? It will improve its binary size. According to my quick local test (one of the latest `pgrx` versions, Fedora 40, Rustc 1.82), enabling `lto = true` for this Cargo extension reduces the binary size from 15 Mib to 11 Mib.

Thank you.

**Comment by workingjubilee** [comment]
You can set build options when building a binary on your own.
