### ISSUE TITLE
Expose `pgstat_count_index_scan` and friends, or make `PgRelation` implement `DerefMut`

### ISSUE THREAD

**Issue by tjgreen42** [pgcentralfoundation/pgrx#1955]
Access method implementations are supposed to call `pgstat_count_index_scan` to keep `pg_stat_user_indexes` up to date, but since this is a `#define` macro rather than a function, there is no wrapper function in `pgrx`.  Meanwhile updating `pgstat_info` directly given a `PgRelation` is not possible because `PgRelation` is not `DerefMut`.

**Comment by tjgreen42** [comment]
It turns out there is a workaround even without `DerefMut` implemented for `PgRelation`, it just requires a temporary variable.  Here is the code I wrote.  It is a bit gnarly.
```rust
/// Hand implementation of `pgstat_count_index_scan`
#[allow(unused_variables)]
pub unsafe fn pgstat_count_index_scan(index_relation: pg_sys::Relation, indexrel: PgRelation) {
    if !indexrel.pgstat_info.is_null() {
        let tmp = indexrel.pgstat_info;
        #[cfg(any(feature = "pg13", feature = "pg14", feature = "pg15"))]
        {
            (*tmp).t_counts.t_numscans += 1;
        }
        #[cfg(any(feature = "pg16", feature = "pg17"))]
        {
            (*tmp).counts.numscans += 1;
        }
    }

    #[cfg(any(feature = "pg15", feature = "pg16", feature = "pg17"))]
    if indexrel.pgstat_info.is_null() && indexrel.pgstat_enabled {
        pgstat_assoc_relation(index_relation);
        assert!(!indexrel.pgstat_info.is_null());
        let tmp = indexrel.pgstat_info;
        #[cfg(feature = "pg15")]
        {
            (*tmp).t_counts.t_numscans += 1;
        }
        #[cfg(any(feature = "pg16", feature = "pg17"))]
        {
            (*tmp).counts.numscans += 1;
        }
    }
}
```

**Comment by eeeebbbbrrrr** [comment]
I noted in #1956 that making `PgRelation` mutable (by implementing `DerefMut`) really isn't the right approach.

What you've done here by hand-porting the `pgstat_count_*` macro to Rust is really the right approach.  If you'd like to do this for all seven of them, I'd happily accept a PR.

**Comment by YohDeadfall** [comment]
Should then the issue be reopened or another one created mentioning these macros?
