### ISSUE TITLE
How to run the ci tests in local env?

### ISSUE THREAD

**Issue by roseduan** [pgcentralfoundation/pgrx#1957]
How to run the ci tests in local env?

**Comment by workingjubilee** [comment]
`cargo test --features "pg14"` or so

**Comment by eeeebbbbrrrr** [comment]
The `cargo-pgrx` README (https://github.com/pgcentralfoundation/pgrx/blob/develop/cargo-pgrx/README.md#testing-your-extension) also discusses how to test extensions.  Our `pgrx-tests` crate is itself an extension, so those instructions also apply here.

But as Jubilee pointed out, `cargo test --features pgXX,pg_test` from the root of the `pgrx` repo should test everything.
