### ISSUE TITLE
Reading / writing Postgres block files

### ISSUE THREAD

**Issue by ccleve** [pgcentralfoundation/pgrx#294]
Postgres stores data in files of 8k block, and has primitives for reading, writing, and locking these files. Has pgx wrapped any of that functionality? Is there any sample code?

**Comment by eeeebbbbrrrr** [comment]
pgx has not wrapped any of that.  I'm not sure if the bindings are there for everything either.  

If they're not, send us a list of the headers you need and we'll cut a new release.  Or feel free to edit pgx' `include/*.h` files and send us a PR.
