### ISSUE TITLE
Adding missing postgres headers to bindings

### ISSUE THREAD

**Issue by Termina1** [pgcentralfoundation/pgrx#310]
I'm trying to write FDW using pgx. I found out that:
```
pg_foreign_server.h
pg_foreign_table.h
```
are not included in the bindings generation. Is it possible to add them, so I could use constants defined there.

**Comment by eeeebbbbrrrr** [comment]
Thanks. I’ll take a look at this next week. If you want to save some time feel free to edit pgx’ include/*.h files and put up a PR.

**Comment by Termina1** [comment]
Ok, I'm planning to make a PR with few patches for better support of FDW. I'll include those changes in the PR.
