### ISSUE TITLE
`#[pg_extern]` needs to support the `COST` property

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [pgcentralfoundation/pgrx#369]
for example:

```
  |
5 | #[pg_extern(immutable, parallel_safe, cost = "1000000.0")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | |
  | expected expression
  | while parsing this struct
  |
  = note: this error originates in the attribute macro `pg_extern` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Specifically, it's the `COST` property here:  https://www.postgresql.org/docs/current/sql-createfunction.html

(as an aside, we ought to support all the options, but I need COST sooner rather than later.

**Comment by Hoverbear** [comment]
> (as an aside, we ought to support all the options,)

I agree. We did this in #230 which is nice
