### ISSUE TITLE
`cargo pgx new` doesn't need to check for `-`'s

### ISSUE THREAD

**Issue by Hoverbear** [pgcentralfoundation/pgrx#457]
@eeeebbbbrrrr mentioned that you cannot `cargo pgx new foo-bar`:

```bash
ana@autonoma:~/git/zombodb/pgx/pgx-examples/bad-ideas$ cargo pgx new foo-bar
Error: 
   0: Extension name must be in the set of [a-z0-9_]

Location:
   cargo-pgx/src/command/new.rs:34

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: cargo_pgx::command::new::execute
      at cargo-pgx/src/command/new.rs:23
```

We can allow dashes, as our backend machinery will convert it to `_`.

**Comment by workingjubilee** [comment]
Obviously this was trivial to implement but I thought about it for five additional seconds and realized that by choosing to canonize names instead of rejecting them, we make it **much** harder to write shell-scripts, batch files, and so on that invoke `cargo pgrx new`. So nah. Closing this.
