### ISSUE TITLE
More numeric type support

### ISSUE THREAD

**Issue by Hoverbear** [pgcentralfoundation/pgrx#497]
We'd like PGX to have improved numeric type support.

We currently have a `String` backed `pgx::datum::Numeric` type:

https://github.com/tcdi/pgx/blob/6184a95523c2eb6da0830413b6e62e2ac24bf90a/pgx/src/datum/numeric.rs#L13-L14

This type has support for `Into` for many Rust types:

https://github.com/tcdi/pgx/blob/6184a95523c2eb6da0830413b6e62e2ac24bf90a/pgx/src/datum/numeric.rs#L88-L98

It is equivalent to the `NUMERIC` type described in [PostgreSQL numeric types](https://www.postgresql.org/docs/current/datatype-numeric.html).

We'd like to support other types also described on the page, such as `bigserial`, `real`, and `smallint`.

## Arbitrary Precision numerics

PostgreSQL also supports arbitrary precision numbers. (https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL). They're already covered by our existing `pgx::datum::Numeric`.

## Special cases

`numeric` can also be `Infinity`, `-Infinity`, or `NaN`.

These values **are not** applicable to `smallint`, `integer`, `bigint`, `smallserial`, `serial`, `bigserial`.

But it's worth noting these values are applicable to `decimal`, `numeric`, `real` and `double precision`.

## Approach

In order to avoid any inconsistency between PostgreSQL, Rust, and pgx itself, we'd like to wrap around Postgres's internal support functions.

**Comment by johnrballard** [comment]
## Task

-[ ] #615
