### ISSUE TITLE
Aggregates incorrectly schema STYPE when using a schema

### ISSUE THREAD

**Issue by mhov** [pgcentralfoundation/pgrx#797]
I'm trying to use an aggregate function with an `STYPE = internal`
I set the global schema in the .control file like this.  (please excuse the anonymized names)
`my_ext.control`
```
...
schema = my_schema
```

and in my `my_agg_func.rs` file i have 
```
type State = Internal;
```

The generated SQL looks like this 
```
CREATE AGGREGATE my_schema.my_agg_func (
    "p_dim_bits" INT[] 
)
(
    SFUNC = my_schema."my_agg_func", /* my_ext::funcs::my_agg_func::AggDimBitsOr::state */
    STYPE = my_schema.internal, /* pgx::datum::internal::Internal */
    INITCOND = '{}' /* my_ext::funcs::my_agg_func::AggDimBitsOr::INITIAL_CONDITION */
);
```

So `STYPE = my_schema.internal` is improperly schema'd  due to this line
https://github.com/tcdi/pgx/blob/18955c7b46afa3e1140433206ebba3929c7d008b/pgx-utils/src/sql_entity_graph/aggregate/entity.rs#L332

The `{schema}` would probably have to be conditional on whether it's a native PG type vs a custom/composite type.

**Comment by workingjubilee** [comment]
This is because `type State = Internal;` declares an alias, not a true type definition. It is effectively no more of a type definition than
```c
#define State Internal
```
would be, which also creates a name that evaporates during compilation.
I am not sure we can fix this. If you want a true newtype, it would require writing
```rust
struct State(Internal);
```

**Comment by mhov** [comment]
this also happened when i had 
```
type State = Array<i32>;
```
it generated 
```
STYPE = my_schema.int[]
```

**Comment by workingjubilee** [comment]
Right, that's what I would expect. Erm. What's the desired behavior, exactly?

**Comment by mhov** [comment]
if in an Aggregate I set 
```
type State = SomeType;
```
if `SomeType` belongs to my schema (custom composite type) and my extension has a schema then the generated CREATE AGGREGATE sql should look like 
```
STYPE = my_schema.SomeType
```
which it does, but if `SomeType` belongs to PG (ex. `internal`, `int[]`, `text`) then generate sql should look like
```
STYPE = SomeType
```
instead of the observed 
```
STYPE = my_schema.SomeType
```

**Comment by workingjubilee** [comment]
got it! Okay it's not the aliasing problem I was confused about.
