### ISSUE TITLE
Breaking changes for 0.6.0

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#821]
We have removed support for Postgres 10:
- [x] pg10: https://github.com/tcdi/pgx/pull/830

Other breaking changes:
- It is possible https://github.com/tcdi/pgx/pull/708 breaks if type inference fails.
- https://github.com/tcdi/pgx/pull/847
- https://github.com/tcdi/pgx/pull/831
- Total revamp of error-handling: https://github.com/tcdi/pgx/pull/834
- https://github.com/tcdi/pgx/pull/886
- https://github.com/tcdi/pgx/pull/894
- Spi signature changes:
  - https://github.com/tcdi/pgx/pull/896
  - https://github.com/tcdi/pgx/pull/897
  - https://github.com/tcdi/pgx/pull/898
  - https://github.com/tcdi/pgx/pull/900
- https://github.com/tcdi/pgx/pull/864
- Some reexports are removed: expect less reexports from `pgx-pg-sys` in general. Notably `pgx::Datum` is now `pg_sys::Datum`!

**Comment by Smittyvb** [comment]
Just to note: the PR that removes the old versions will probably conflict a lot with #729 (which adds pg15 support), so it might make sense to get that PR in before removing the old versions.

**Comment by Smittyvb** [comment]
I'm fine with dropping 10/11 (just checked, nothing at Timescale supports those versions anyways). We do still need to support Postgres 12, so it would be nice if pgx could retain support for that version.

**Comment by eeeebbbbrrrr** [comment]
Sure thing. No worries.  We’ve not yet convinced ourselves that 11 should go.

**Comment by workingjubilee** [comment]
I think we should have good reasons for retaining support for _any_ version rather than simply "because it's there". However, obviously a request from a user who needs it qualifies.

**Comment by Smittyvb** [comment]
I noticed that 500e3a2ba289da9cbfd1d784c029a877c3c5af0f removed some reexports from `pgx`:
```diff,rust
 pub use pgx_pg_sys as pg_sys; // the module only, not its contents
-pub use pgx_pg_sys::submodules::*;
-pub use pgx_pg_sys::PgBuiltInOids; // reexport this so it looks like it comes from here
```

Most notably, this breaks usage of `pgx::Datum` – now `pg_sys::Datum` is needed instead. This should be added to the list of breaking changes.
